# Section 1: Install Required Libraries

In [7]:
pip install --upgrade --force-reinstall Pillow

Collecting Pillow
  Downloading pillow-12.3.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Downloading pillow-12.3.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 22.8 MB/s  0:00:00
Installing collected packages: Pillow
  Attempting uninstall: Pillow
    Found existing installation: pillow 12.2.0
    Uninstalling pillow-12.2.0:
      Successfully uninstalled pillow-12.2.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
unsloth-zoo 2026.7.2 requires datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1, but you have datasets 5.0.0 which is incompatible.
unsloth-zoo 2026.7.2 requires trl!=0.19.0,<=0.24.0,>=0.18.2; sys_platform != "darwin" or platform_machine != "arm64", but you have trl 1.8.0 which is incompatible.
Successfully installed Pillow-12.3.0

In [2]:
# COMPLETE FRESH START - Remove everything and reinstall cleanly
import subprocess
import sys

# Uninstall ALL ML packages to ensure a clean slate
packages_to_remove = ['unsloth', 'transformers', 'datasets', 'trl', 'peft', 'bitsandbytes', 'xformers', 'Pillow']
for pkg in packages_to_remove:
    subprocess.run([sys.executable, '-m', 'pip', 'uninstall', '-y', pkg],
                   capture_output=True, timeout=60)

print("✓ Removed old packages")

# Fresh pip cache
subprocess.run(['pip', 'cache', 'purge'], capture_output=True, timeout=30)
print("✓ Cleared pip cache")

# Install minimal dependencies first
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', 'pip'],
               capture_output=True, timeout=60)

# Install PyTorch (matching the reported CUDA version if possible)
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--no-cache-dir',
                'torch', 'torchvision', 'torchaudio',
                '--index-url', 'https://download.pytorch.org/whl/cu121'], # Changed to cu121 as that's what unsloth typically uses with recent PyTorch
               capture_output=True, timeout=120)
print("✓ PyTorch installed")

# Install unsloth, which will bring its own compatible versions of transformers, peft, trl, etc.
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--no-cache-dir',
                'unsloth[cu121]'], # Explicitly install unsloth for cu121
               capture_output=True, timeout=120)
print("✓ Unsloth installed (including its dependencies like transformers, peft, trl)")

# Finally other general libraries that might not be directly managed by unsloth
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--no-cache-dir',
                'pymupdf', 'pandas', 'numpy', 'scikit-learn',
                'pdfplumber', 'packaging'],
               capture_output=True, timeout=120)
print("✓ Other libraries installed")

# Verify imports
print("\n=== VERIFICATION ===")
try:
    import torch
    print(f"✓ PyTorch {torch.__version__}")
    import transformers
    print(f"✓ Transformers {transformers.__version__}")
    from unsloth import FastLanguageModel
    print(f"✓ Unsloth imported successfully")
    print(f"✓ GPU Available: {torch.cuda.is_available()}")
except Exception as e:
    print(f"✗ Import failed: {e}")

✓ Removed old packages
✓ Cleared pip cache
✓ PyTorch installed
✓ Unsloth installed (including its dependencies like transformers, peft, trl)
✓ Other libraries installed

=== VERIFICATION ===
✓ PyTorch 2.11.0+cu128
✗ Import failed: No module named 'transformers'

In [3]:
# Install Unsloth and its core Colab dependencies
!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"

# Install complementary training and utility libraries
!pip install --no-deps xformers "trl<0.9.0" peft accelerate bitsandbytes

Collecting unsloth @ git+https://github.com/unslothai/unsloth.git (from unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Cloning https://github.com/unslothai/unsloth.git to /tmp/pip-install-xpg170mv/unsloth_02a48a19a4c34aeab3edb28633da6f3e
  Running command git clone --filter=blob:none --quiet https://github.com/unslothai/unsloth.git /tmp/pip-install-xpg170mv/unsloth_02a48a19a4c34aeab3edb28633da6f3e
  Resolved https://github.com/unslothai/unsloth.git to commit d105bd7b42ea8d4ecdb3e3364abb605b558c017e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.25.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (13.9.4)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.13.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (6.0.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.6.0)
Collecting unsloth_zoo>=2026.7.2 (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Downloading unsloth_zoo-2026.7.2-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (26.2)
Collecting tyro (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Downloading tyro-1.0.15-py3-none-any.whl.metadata (12 kB)
Collecting transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3 (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Downloading transformers-5.5.0-py3-none-any.whl.metadata (32 kB)
Collecting datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Downloading datasets-4.3.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.2.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (5.9.5)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.47.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.0.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (5.29.6)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.20.1)
Collecting hf_transfer (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (5.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.29.4)
Collecting pyarrow>=21.0.0 (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.7.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2025.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.16.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (4.15.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.8.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.24.2)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.11.0+cu128)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (12.8.90)

In [4]:
pip install -U trl

Requirement already satisfied: trl in /usr/local/lib/python3.12/dist-packages (0.8.6)
Collecting trl
  Downloading trl-1.8.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: accelerate>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from trl) (1.14.0)
Collecting datasets>=4.7.0 (from trl)
  Downloading datasets-5.0.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: packaging>20.0 in /usr/local/lib/python3.12/dist-packages (from trl) (26.2)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl) (5.5.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.11.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (1.20.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (0.8.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.29.4)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (25.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.7.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2025.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.7.0->trl) (0.16.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.5.1)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.15.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.24.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.1.2)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.1)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.0.0->accelerate>=1.4.0->trl) (1.5.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.4.0->trl) (1.3.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.22.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.7.0->trl) (1.17.0)
Downloading trl-1.8.0-py3-none-any.whl (863 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 863.2/863.2 kB 8.2 MB/s  0:00:00
Downloading datasets-5.0.0-py3-none-any.whl (555 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 555.1/555.1 kB 7.7 MB/s  0:00:00
Installing collected packages: datasets, trl
  Attempting uninstall: datasets
    Found existing installation: datasets 4.3.0
    Uninstalling datasets-4.3.0:
      Successfully uninstalled datasets-4.3.0
  Attempting uninstall: trl
    Found existing installation: trl 0.8.6
    Uninstalling trl-0.8.6:
      Successfully uninstalled trl-0.8.6
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [trl]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
unsloth-zoo 2026.7.2 requires datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1, but you have datasets 5.0.0 which is incompatible.
unsloth-zoo 2026.7.2 requires trl!=0.19.0,<=0.24.0,>=0.18.2; sys_platform != "darwin" or platform_machine != "arm64", but you have trl 1.8.0 which is incompatible.
Successfully installed datasets-5.0.0 trl-1.8.0

In [5]:
pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.5.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.20.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)

In [1]:
# Import required libraries
import os
import re
import gc
import json
import time
import warnings
import unicodedata
from typing import List, Dict, Any, Tuple
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import fitz  # PyMuPDF

from datasets import Dataset, load_dataset
from transformers import TextIteratorStreamer # This should now be available
from threading import Thread

# Unsloth imports (moved here for consolidation after installation)
import unsloth
from unsloth import FastLanguageModel, is_bfloat16_supported
from unsloth.chat_templates import get_chat_template

# Training imports (if needed, otherwise remove)
from trl import SFTTrainer, SFTConfig # This should now be available

warnings.filterwarnings("ignore")

# Verify GPU availability
assert torch.cuda.is_available(), "GPU not found. Please ensure CUDA is available."
print(f"✓ GPU Available: {torch.cuda.get_device_name(0)}")
print(f"✓ CUDA Version: {torch.version.cuda}")
print(f"✓ PyTorch Version: {torch.__version__}")

/usr/local/lib/python3.12/dist-packages/unsloth/__init__.py:1427: UserWarning: WARNING: Unsloth should be imported before [transformers] to ensure all optimizations are applied. Your code may run slower or encounter memory issues without these optimizations.

Please restructure your imports with 'import unsloth' at the top of your file.
  from ._gpu_init import *

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

Accessing `is_flash_linear_attention_available` from `.models.aria.image_processing_aria`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.aria.image_processing_pil_aria`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.auto.image_processing_auto`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.beit.image_processing_beit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.beit.image_processing_pil_beit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.bit.image_processing_bit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.bit.image_processing_pil_bit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.blip.image_processing_blip`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.blip.image_processing_pil_blip`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.bridgetower.image_processing_bridgetower`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.bridgetower.image_processing_pil_bridgetower`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.chameleon.image_processing_chameleon`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.chameleon.image_processing_pil_chameleon`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.chinese_clip.image_processing_chinese_clip`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.chinese_clip.image_processing_chinese_pil_clip`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.chmv2.image_processing_chmv2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.clip.image_processing_clip`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.clip.image_processing_pil_clip`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.cohere2_vision.image_processing_cohere2_vision`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.conditional_detr.image_processing_conditional_detr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.conditional_detr.image_processing_pil_conditional_detr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.convnext.image_processing_convnext`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.convnext.image_processing_pil_convnext`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deepseek_vl.image_processing_deepseek_vl`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deepseek_vl.image_processing_pil_deepseek_vl`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deepseek_vl_hybrid.image_processing_deepseek_vl_hybrid`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deepseek_vl_hybrid.image_processing_pil_deepseek_vl_hybrid`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deformable_detr.image_processing_deformable_detr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deformable_detr.image_processing_pil_deformable_detr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deit.image_processing_deit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deit.image_processing_pil_deit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.depth_pro.image_processing_depth_pro`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.detr.image_processing_detr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.detr.image_processing_pil_detr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.dinov3_vit.image_processing_dinov3_vit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.donut.image_processing_donut`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.donut.image_processing_pil_donut`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.dpt.image_processing_dpt`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.dpt.image_processing_pil_dpt`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.efficientloftr.image_processing_efficientloftr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.efficientloftr.image_processing_pil_efficientloftr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.efficientnet.image_processing_efficientnet`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.efficientnet.image_processing_pil_efficientnet`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.emu3.image_processing_emu3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.eomt.image_processing_eomt`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.eomt.image_processing_pil_eomt`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.ernie4_5_vl_moe.image_processing_ernie4_5_vl_moe`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.ernie4_5_vl_moe.image_processing_pil_ernie4_5_vl_moe`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.flava.image_processing_flava`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.flava.image_processing_pil_flava`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.fuyu.image_processing_fuyu`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.fuyu.image_processing_pil_fuyu`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.gemma3.image_processing_gemma3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.gemma3.image_processing_pil_gemma3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.gemma4.image_processing_gemma4`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.gemma4.image_processing_pil_gemma4`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glm46v.image_processing_glm46v`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glm46v.image_processing_pil_glm46v`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glm4v.image_processing_glm4v`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glm4v.image_processing_pil_glm4v`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glm_image.image_processing_glm_image`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glm_image.image_processing_pil_glm_image`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glpn.image_processing_glpn`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glpn.image_processing_pil_glpn`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.got_ocr2.image_processing_got_ocr2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.got_ocr2.image_processing_pil_got_ocr2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.grounding_dino.image_processing_grounding_dino`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.grounding_dino.image_processing_pil_grounding_dino`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.idefics.image_processing_idefics`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.idefics.image_processing_pil_idefics`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.idefics2.image_processing_idefics2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.idefics2.image_processing_pil_idefics2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.idefics3.image_processing_idefics3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.idefics3.image_processing_pil_idefics3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.imagegpt.image_processing_imagegpt`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.imagegpt.image_processing_pil_imagegpt`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.janus.image_processing_janus`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.janus.image_processing_pil_janus`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.kosmos2_5.image_processing_kosmos2_5`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.kosmos2_5.image_processing_pil_kosmos2_5`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.layoutlmv2.image_processing_layoutlmv2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.layoutlmv2.image_processing_pil_layoutlmv2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.layoutlmv3.image_processing_layoutlmv3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.layoutlmv3.image_processing_pil_layoutlmv3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.levit.image_processing_levit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.

🦥 Unsloth Zoo will now patch everything to make training faster!
✓ GPU Available: Tesla T4
✓ CUDA Version: 12.8
✓ PyTorch Version: 2.11.0+cu128

# Section 2: Configuration & File Paths

In [2]:
# ==========================================
# Configuration Parameters
# ==========================================

# Model Configuration
BASE_MODEL = "unsloth/tinyllama-bnb-4bit"  # Open source model
# Alternative options:
# "unsloth/llama-2-7b-bnb-4bit"
# "unsloth/tinyllama-bnb-4bit"
# "unsloth/mistral-7b-bnb-4bit"

MAX_SEQ_LENGTH = 2048
SEED = 42

# Data Paths (Google Colab - files from /content folder)
PDF_FILE_PATH = "/content/data.pdf"  # Your PDF file
JSONL_INSTRUCTION_FILE = "/content/instructions.jsonl"  # Your instruction JSONL

# Validate that input files exist
for file_path in [PDF_FILE_PATH, JSONL_INSTRUCTION_FILE]:
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"File not found: {file_path}. Please upload this file to /content folder in Colab.")

# LoRA Configuration
LORA_R = 16  # LoRA rank
LORA_ALPHA = 32  # LoRA alpha
LORA_DROPOUT = 0.05
LORA_TARGET_MODULES = ["q_proj", "k_proj", "v_proj", "o_proj"]

# QLoRA Configuration (for 4-bit quantization - already done via model loading)
USE_QLORA = True  # Already using 4-bit via model name

# Training Configuration
BATCH_SIZE = 2
GRADIENT_ACCUMULATION_STEPS = 4
NUM_TRAIN_EPOCHS = 3
WARMUP_STEPS = 50
LOGGING_STEPS = 10
SAVE_STEPS = 500

# Learning rates for different stages
STAGE1_LR = 2e-4  # Non-instruction fine-tuning
STAGE2_LR = 1e-4  # Instruction fine-tuning

# PDF Processing
MIN_CHARS_PER_CHUNK = 100
CHUNK_OVERLAP = 50

# Output directories (Google Colab)
OUTPUT_DIR = "/content/outputs"
STAGE1_ADAPTER_DIR = f"{OUTPUT_DIR}/stage1_non_instruction_adapter"
STAGE1_MERGED_DIR = f"{OUTPUT_DIR}/stage1_non_instruction_merged"
STAGE2_ADAPTER_DIR = f"{OUTPUT_DIR}/stage2_instruction_adapter"
STAGE2_MERGED_DIR = f"{OUTPUT_DIR}/stage2_instruction_merged"
FINAL_MERGED_DIR = f"{OUTPUT_DIR}/final_merged_model"

# Create output directories
for dir_path in [OUTPUT_DIR, STAGE1_ADAPTER_DIR, STAGE1_MERGED_DIR,
                  STAGE2_ADAPTER_DIR, STAGE2_MERGED_DIR, FINAL_MERGED_DIR]:
    os.makedirs(dir_path, exist_ok=True)

print("✓ Configuration loaded")
print(f"✓ Input files validated from /content folder")
print(f"✓ Output directories created at: {OUTPUT_DIR}")

✓ Configuration loaded
✓ Input files validated from /content folder
✓ Output directories created at: /content/outputs

# Section 3: Utility Functions for PDF Processing & Data Handling

In [3]:
def extract_pdf_text(pdf_path: str) -> List[Dict[str, Any]]:
    """
    Extract text from PDF file with page information

    Args:
        pdf_path: Path to PDF file

    Returns:
        List of dictionaries containing page number and text
    """
    pages = []

    try:
        with fitz.open(pdf_path) as doc:
            for page_num, page in enumerate(doc, start=1):
                text = page.get_text("text").strip()
                if text:
                    pages.append({
                        "page": page_num,
                        "text": text,
                    })
    except Exception as e:
        print(f"Error extracting PDF: {e}")
        return []

    print(f"✓ Extracted {len(pages)} pages from PDF")
    return pages


def clean_text(text: str) -> str:
    """
    Clean and normalize text for training

    Args:
        text: Raw text to clean

    Returns:
        Cleaned text
    """
    # Unicode normalization
    text = unicodedata.normalize("NFKC", text)
    text = text.replace("\u200b", "").replace("\ufeff", "")

    # Fix hyphenated words broken across lines
    text = re.sub(r"(\w)-\n(\w)", r"\1\2", text)

    # Remove page numbers
    text = re.sub(r"(?m)^\s*\d+\s*$", "", text)

    # Normalize spaces
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()


def chunk_text(text: str, chunk_size: int = 512, overlap: int = 50) -> List[str]:
    """
    Split text into overlapping chunks

    Args:
        text: Text to chunk
        chunk_size: Maximum characters per chunk
        overlap: Number of overlapping characters between chunks

    Returns:
        List of text chunks
    """
    chunks = []
    start = 0

    while start < len(text):
        end = min(start + chunk_size, len(text))

        # Try to break at sentence boundary
        if end < len(text):
            last_period = text.rfind(".", start, end)
            if last_period > start:
                end = last_period + 1

        chunk = text[start:end].strip()
        if len(chunk) >= MIN_CHARS_PER_CHUNK:
            chunks.append(chunk)

        start = end - overlap if end < len(text) else end

    return chunks


def clear_gpu_memory():
    """Clear GPU memory cache"""
    gc.collect()
    torch.cuda.empty_cache()


def print_trainable_params(model):
    """Print model trainable vs total parameters"""
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total_params = sum(p.numel() for p in model.parameters())

    print(f"Trainable params: {trainable_params:,} / {total_params:,}")
    print(f"Trainable %: {100 * trainable_params / total_params:.2f}%")

print("✓ Utility functions defined")

✓ Utility functions defined

In [4]:
def create_dataset_from_pdf(pdf_path: str) -> Dataset:
    """
    Create training dataset from PDF file

    Args:
        pdf_path: Path to PDF file

    Returns:
        HuggingFace Dataset
    """
    pages = extract_pdf_text(pdf_path)
    records = []

    for page in pages:
        cleaned_text = clean_text(page["text"])
        chunks = chunk_text(cleaned_text, chunk_size=512, overlap=CHUNK_OVERLAP)

        for chunk_id, chunk in enumerate(chunks):
            if len(chunk) >= MIN_CHARS_PER_CHUNK:
                records.append({
                    "text": chunk,
                    "source_page": page["page"],
                    "chunk_id": chunk_id,
                })

    print(f"✓ Created {len(records)} text chunks from PDF")
    if records:
        print(f"Sample chunk:\n{records[0]['text'][:300]}...")

    return Dataset.from_list(records)


def load_instruction_dataset_from_jsonl(jsonl_path: str) -> Dataset:
    """
    Load instruction dataset from JSONL file

    Args:
        jsonl_path: Path to JSONL file with format:
                   {"instruction": "...", "input": "...", "output": "..."}

    Returns:
        HuggingFace Dataset
    """
    records = []

    try:
        with open(jsonl_path, 'r') as f:
            for line in f:
                if line.strip():
                    record = json.loads(line)
                    # Ensure required fields exist
                    record.setdefault('instruction', '')
                    record.setdefault('input', '')
                    record.setdefault('output', '')
                    records.append(record)
    except Exception as e:
        print(f"Error loading JSONL: {e}")
        return Dataset.from_list([])

    print(f"✓ Loaded {len(records)} instruction examples from JSONL")
    if records:
        print(f"Sample instruction:\n{records[0]}")

    return Dataset.from_list(records)


def format_instruction_prompt(instruction: str, input_text: str = "", output_text: str = "") -> str:
    """
    Format instruction in alpaca-style template

    Args:
        instruction: Main instruction
        input_text: Optional input context
        output_text: Expected output (for training)

    Returns:
        Formatted prompt string
    """
    instruction = str(instruction).strip()
    input_text = str(input_text).strip()
    output_text = str(output_text).strip()

    if input_text:
        prompt = f"### Instruction:\n{instruction}\n\n### Input:\n{input_text}\n\n### Response:\n{output_text}"
    else:
        prompt = f"### Instruction:\n{instruction}\n\n### Response:\n{output_text}"

    return prompt


def format_instruction_dataset(dataset: Dataset) -> Dataset:
    """
    Format instruction dataset with proper prompts

    Args:
        dataset: Raw instruction dataset

    Returns:
        Formatted dataset with 'text' field
    """
    def format_row(row):
        prompt = format_instruction_prompt(
            instruction=row.get('instruction', ''),
            input_text=row.get('input', ''),
            output_text=row.get('output', '')
        )
        return {"text": prompt}

    formatted = dataset.map(format_row, remove_columns=dataset.column_names)
    print(f"✓ Formatted {len(formatted)} instruction examples")
    if len(formatted) > 0:
        print(f"Sample formatted text:\n{formatted[0]['text'][:300]}...")

    return formatted

print("✓ PDF and instruction processing functions defined")

✓ PDF and instruction processing functions defined

# Section 4: Load Tokenizer and Model with LoRA/QLoRA

In [5]:
def load_model_with_lora(model_name_or_path: str, load_in_4bit: bool = True):
    """
    Load model with LoRA/QLoRA configuration using Unsloth

    Args:
        model_name_or_path: Model name or path
        load_in_4bit: Whether to use 4-bit quantization (QLoRA)

    Returns:
        Tuple of (model, tokenizer)
    """
    print(f"\nLoading model: {model_name_or_path}")
    print(f"4-bit Quantization (QLoRA): {load_in_4bit}")

    # Load model and tokenizer using Unsloth
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=model_name_or_path,
        max_seq_length=MAX_SEQ_LENGTH,
        dtype=None,
        load_in_4bit=load_in_4bit,
    )

    # Setup tokenizer
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    # Apply LoRA configuration
    print("\nApplying LoRA configuration:")
    print(f"  LoRA Rank (r): {LORA_R}")
    print(f"  LoRA Alpha: {LORA_ALPHA}")
    print(f"  LoRA Dropout: {LORA_DROPOUT}")

    model = FastLanguageModel.get_peft_model(
        model,
        r=LORA_R,
        lora_alpha=LORA_ALPHA,
        target_modules=LORA_TARGET_MODULES,
        lora_dropout=LORA_DROPOUT,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=SEED,
    )

    print("\nModel loaded successfully!")
    print_trainable_params(model)

    return model, tokenizer


# Load base model
print("=" * 60)
print("LOADING BASE MODEL")
print("=" * 60)

base_model, base_tokenizer = load_model_with_lora(BASE_MODEL, load_in_4bit=True)
clear_gpu_memory()

print("\n✓ Base model ready for training")

============================================================
LOADING BASE MODEL
============================================================

Loading model: unsloth/tinyllama-bnb-4bit
4-bit Quantization (QLoRA): True
==((====))==  Unsloth 2026.7.2: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Unsloth: Will load unsloth/tinyllama-bnb-4bit as a legacy tokenizer.
Unsloth: Dropout = 0 is supported for fast patching. You are using dropout = 0.05.
Unsloth will patch all other layers, except LoRA matrices, causing a performance hit.

Applying LoRA configuration:
  LoRA Rank (r): 16
  LoRA Alpha: 32
  LoRA Dropout: 0.05

Unsloth 2026.7.2 patched 22 layers with 0 QKV layers, 0 O layers and 0 MLP layers.

Model loaded successfully!
Trainable params: 4,505,600 / 620,111,872
Trainable %: 0.73%

✓ Base model ready for training

# Section 5: Extract and Process PDF Text

In [6]:
# Check if PDF exists, if not create a sample dataset
if os.path.exists(PDF_FILE_PATH):
    print(f"Loading PDF from: {PDF_FILE_PATH}")
    pdf_dataset = create_dataset_from_pdf(PDF_FILE_PATH)
else:
    print(f"⚠ PDF file not found at {PDF_FILE_PATH}")
    print("Creating sample dataset for demonstration...")

    # Create sample data for demonstration
    sample_texts = [

        "The X-ray tube generates radiation that passes through the patient while detectors convert transmitted photons into electrical signals."
         "Common failures include tube arcing, tube overheating, detector calibration drift,"
        "DAS communication faults, gantry rotation errors, chiller malfunction, encoder faults, slip-ring wear and table motion problems",

        "A CT scanner consists of the gantry, X-ray tube, high-voltage generator, detector array, data acquisition system, slip ring, cooling system, patient table, reconstruction computers and operator console. "
        "The X-ray tube generates radiation that passes through the patient while detectors convert transmitted photons into electrical signals. "
        "Common failures include tube arcing, tube overheating, detector calibration drift, DAS communication faults, gantry rotation errors, chiller malfunction, encoder faults, slip-ring wear and table motion problems. "
        "Ring artifacts usually indicate detector calibration issues or failed detector channels." ,


        "A CT scanner consists of the gantry, X-ray tube, high-voltage generator, detector array, data acquisition system, slip ring, "
        "cooling system, patient table, reconstruction computers and operator console."
        "The X-ray tube generates radiation that passes through the patient while detectors convert transmitted photons into electrical signals",
    ]

    records = [{"text": text, "source_page": i, "chunk_id": 0}
               for i, text in enumerate(sample_texts, 1)]
    pdf_dataset = Dataset.from_list(records)
    print(f"✓ Created sample dataset with {len(pdf_dataset)} examples")

print(f"\n✓ Dataset size: {len(pdf_dataset)} samples")
print(f"Sample text:\n{pdf_dataset[0]['text'][:250]}...")

Loading PDF from: /content/data.pdf
✓ Extracted 137 pages from PDF
✓ Created 1411 text chunks from PDF
Sample chunk:
Medical Imaging Equipment Failure Diagnosis Knowledge Base
Introduction
This handbook provides domain-specific knowledge for troubleshooting CT scanners, MRI
systems, ultrasound systems, digital radiography, mammography, fluoroscopy, C-arms and
PET/CT systems. It explains major subsystems, opera...

✓ Dataset size: 1411 samples
Sample text:
Medical Imaging Equipment Failure Diagnosis Knowledge Base
Introduction
This handbook provides domain-specific knowledge for troubleshooting CT scanners, MRI
systems, ultrasound systems, digital radiography, mammography, fluoroscopy, C-arms and
P...

# Section 6: Stage 1 - Non-Instruction Fine-Tuning on Raw PDF Text

In [7]:
print("\n" + "=" * 60)
print("STAGE 1: NON-INSTRUCTION FINE-TUNING")
print("Training on raw PDF text")
print("=" * 60)

# Reload model for training
clear_gpu_memory()
stage1_model, tokenizer = load_model_with_lora(BASE_MODEL, load_in_4bit=True)

# Configure training
stage1_config = SFTConfig(
    output_dir=f"{OUTPUT_DIR}/stage1_logs",
    num_train_epochs=NUM_TRAIN_EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
    learning_rate=STAGE1_LR,
    warmup_steps=WARMUP_STEPS,
    logging_steps=LOGGING_STEPS,
    save_strategy="steps",
    save_steps=SAVE_STEPS,
    report_to="none",
    fp16=not is_bfloat16_supported(),
    bf16=is_bfloat16_supported(),
    optim="adamw_8bit",
    dataset_text_field="text",
    max_seq_length=MAX_SEQ_LENGTH,
    packing=True,
    seed=SEED,
)

print("\nTraining Configuration:")
print(f"  Epochs: {NUM_TRAIN_EPOCHS}")
print(f"  Batch Size: {BATCH_SIZE}")
print(f"  Learning Rate: {STAGE1_LR}")
print(f"  Max Seq Length: {MAX_SEQ_LENGTH}")

# Create trainer
stage1_trainer = SFTTrainer(
    model=stage1_model,
    tokenizer=tokenizer,
    train_dataset=pdf_dataset,
    args=stage1_config,
)

# Train
print("\nStarting Stage 1 training...")
start_time = time.time()
stage1_train_result = stage1_trainer.train()
training_time = time.time() - start_time

print(f"\n✓ Stage 1 Training Complete!")
print(f"Training time: {training_time:.2f}s")
print(f"Final loss: {stage1_train_result.training_loss:.4f}")

# Save adapter
print(f"\nSaving Stage 1 adapter to: {STAGE1_ADAPTER_DIR}")
stage1_model.save_pretrained(STAGE1_ADAPTER_DIR)
tokenizer.save_pretrained(STAGE1_ADAPTER_DIR)

# Save merged model
print(f"Saving Stage 1 merged model to: {STAGE1_MERGED_DIR}")
stage1_model.save_pretrained_merged(
    STAGE1_MERGED_DIR,
    tokenizer,
    save_method="merged_16bit",
)

print("\n✓ Stage 1 artifacts saved")
clear_gpu_memory()

============================================================
STAGE 1: NON-INSTRUCTION FINE-TUNING
Training on raw PDF text
============================================================

Loading model: unsloth/tinyllama-bnb-4bit
4-bit Quantization (QLoRA): True
==((====))==  Unsloth 2026.7.2: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Unsloth: Will load unsloth/tinyllama-bnb-4bit as a legacy tokenizer.

Applying LoRA configuration:
  LoRA Rank (r): 16
  LoRA Alpha: 32
  LoRA Dropout: 0.05

Model loaded successfully!
Trainable params: 4,505,600 / 620,111,872
Trainable %: 0.73%

Training Configuration:
  Epochs: 3
  Batch Size: 2
  Learning Rate: 0.0002
  Max Seq Length: 2048

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/1411 [00:00<?, ? examples/s]

Unsloth: Packing train dataset (num_proc=6):   0%|          | 0/1411 [00:00<?, ? examples/s]

🦥 Unsloth: Packing enabled - training is >2x faster and uses less VRAM!

Starting Stage 1 training...

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 79 | Num Epochs = 3 | Total steps = 30
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 4,505,600 of 1,104,553,984 (0.41% trained)
`use_return_dict` is deprecated! Use `return_dict` instead!

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

Unsloth: Restored added_tokens_decoder metadata in /content/outputs/stage1_logs/checkpoint-30/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in /content/outputs/stage1_logs/checkpoint-30.

✓ Stage 1 Training Complete!
Training time: 223.29s
Final loss: 3.2288

Saving Stage 1 adapter to: /content/outputs/stage1_non_instruction_adapter

Unsloth: Restored added_tokens_decoder metadata in /content/outputs/stage1_non_instruction_adapter/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in /content/outputs/stage1_non_instruction_adapter.

Saving Stage 1 merged model to: /content/outputs/stage1_non_instruction_merged

config.json:   0%|          | 0.00/749 [00:00<?, ?B/s]

Unsloth: Restored added_tokens_decoder metadata in /content/outputs/stage1_non_instruction_merged/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in /content/outputs/stage1_non_instruction_merged.

Found HuggingFace hub cache directory: /root/.cache/huggingface/hub
Checking cache directory for required files...
Cache check failed: model.safetensors not found in local cache.
Not all required files found in cache. Will proceed with downloading.
Checking cache directory for required files...
Cache check failed: tokenizer.model not found in local cache.
Not all required files found in cache. Will proceed with downloading.

Unsloth: Preparing safetensor model files:   0%|          | 0/1 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/2.20G [00:00<?, ?B/s]

Unsloth: Preparing safetensor model files: 100%|██████████| 1/1 [00:27<00:00, 27.50s/it]
Unsloth: Merging weights into 16bit: 100%|██████████| 1/1 [00:17<00:00, 17.71s/it]

Unsloth: Merge process complete. Saved to `/content/outputs/stage1_non_instruction_merged`

✓ Stage 1 artifacts saved

# Section 7: Load and Process Instruction Dataset from JSONL

In [8]:
# Load instruction dataset
if os.path.exists(JSONL_INSTRUCTION_FILE):
    print(f"Loading instruction dataset from: {JSONL_INSTRUCTION_FILE}")
    instruction_dataset = load_instruction_dataset_from_jsonl(JSONL_INSTRUCTION_FILE)
    if not instruction_dataset and os.path.exists(JSONL_INSTRUCTION_FILE): # Check if loading failed but file exists
        print("⚠ Failed to load instruction JSONL, using sample dataset instead.")
        sample_instructions = [
            {
                "instruction": "What causes CT Scanner failure scenario?",
                "input": "",
                "output": "Common causes include power issues, cooling problems, cable damage, component aging, calibration drift, communication faults, or mechanical wear. Diagnosis should begin with visual inspection and system logs. "
            },
            {
                "instruction": "What preventive maintenance is required for Ultrasound item",
                "input": "",
                "output": "Perform routine cleaning, inspect connectors, verify calibration, check cooling performance, review logs, and replace worn consumables according to maintenance schedules. "
            },
            {
                "instruction": "What is the function of the PET-CT component ?",
                "input": "",
                "output": "The referenced component in the PET-CT performs its designated operational role and should be inspected according to the service manual if abnormal behavior is observed. "
            },
            {
                "instruction": "What is the function of the Mammography component ?",
                "input": "",
                "output": "The referenced component in the Mammography performs its designated operational role and should be inspected according to the service manual if abnormal behavior is observed."
            },
            {
                "instruction": "Why is image quality degraded on MRI case?",
                "input": "",
                "output": "Image degradation may result from calibration errors, detector or probe issues, motion artifacts, electronic noise, or reconstruction problems."
            },
        ]
        instruction_dataset = Dataset.from_list(sample_instructions)
        print(f"✓ Created sample instruction dataset with {len(instruction_dataset)} examples")
else:
    print(f"⚠ Instruction JSONL file not found at {JSONL_INSTRUCTION_FILE}")
    print("Creating sample instruction dataset for demonstration...")

    # Create sample instruction dataset
    sample_instructions = [
        {
            "instruction": "What causes CT Scanner failure scenario?",
            "input": "",
            "output": "Common causes include power issues, cooling problems, cable damage, component aging, calibration drift, communication faults, or mechanical wear. Diagnosis should begin with visual inspection and system logs. "
        },
        {
            "instruction": "What preventive maintenance is required for Ultrasound item",
            "input": "",
            "output": "Perform routine cleaning, inspect connectors, verify calibration, check cooling performance, review logs, and replace worn consumables according to maintenance schedules. "
        },
        {
            "instruction": "What is the function of the PET-CT component ?",
            "input": "",
            "output": "The referenced component in the PET-CT performs its designated operational role and should be inspected according to the service manual if abnormal behavior is observed. "
        },
        {
            "instruction": "What is the function of the Mammography component ?",
            "input": "",
            "output": "The referenced component in the Mammography performs its designated operational role and should be inspected according to the service manual if abnormal behavior is observed."
        },
        {
            "instruction": "Why is image quality degraded on MRI case?",
            "input": "",
            "output": "Image degradation may result from calibration errors, detector or probe issues, motion artifacts, electronic noise, or reconstruction problems."
        },
    ]

    instruction_dataset = Dataset.from_list(sample_instructions)
    print(f"✓ Created sample instruction dataset with {len(instruction_dataset)} examples")

# Format the instruction dataset
formatted_instruction_dataset = format_instruction_dataset(instruction_dataset)

print(f"\n✓ Formatted instruction dataset: {len(formatted_instruction_dataset)} samples")
# Only attempt to print sample if the dataset is not empty
if len(formatted_instruction_dataset) > 0:
    print(f"Sample formatted example:\n{formatted_instruction_dataset[0]['text'][:400]}...")

Loading instruction dataset from: /content/instructions.jsonl
✓ Loaded 300 instruction examples from JSONL
Sample instruction:
{'instruction': 'What is the function of the CT Scanner component 1?', 'input': '', 'output': 'The referenced component in the CT Scanner performs its designated operational role and should be inspected according to the service manual if abnormal behavior is observed.', 'source_page': 1, 'topic': 'CT Scanner - Components'}

Map:   0%|          | 0/300 [00:00<?, ? examples/s]

✓ Formatted 300 instruction examples
Sample formatted text:
### Instruction:
What is the function of the CT Scanner component 1?

### Response:
The referenced component in the CT Scanner performs its designated operational role and should be inspected according to the service manual if abnormal behavior is observed....

✓ Formatted instruction dataset: 300 samples
Sample formatted example:
### Instruction:
What is the function of the CT Scanner component 1?

### Response:
The referenced component in the CT Scanner performs its designated operational role and should be inspected according to the service manual if abnormal behavior is observed....

# Section 8: Stage 2 - Instruction-Based Fine-Tuning

In [9]:
print("\n" + "=" * 60)
print("STAGE 2: INSTRUCTION-BASED FINE-TUNING")
print("Training on formatted instruction data")
print("=" * 60)

# Load the Stage 1 merged model as starting point
clear_gpu_memory()
print(f"\nLoading Stage 1 merged model from: {STAGE1_MERGED_DIR}")
stage2_model, tokenizer = load_model_with_lora(STAGE1_MERGED_DIR, load_in_4bit=True)

# Configure training for instruction fine-tuning
stage2_config = SFTConfig(
    output_dir=f"{OUTPUT_DIR}/stage2_logs",
    num_train_epochs=NUM_TRAIN_EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
    learning_rate=STAGE2_LR,
    warmup_steps=WARMUP_STEPS,
    logging_steps=LOGGING_STEPS,
    save_strategy="steps",
    save_steps=SAVE_STEPS,
    report_to="none",
    fp16=not is_bfloat16_supported(),
    bf16=is_bfloat16_supported(),
    optim="adamw_8bit",
    dataset_text_field="text",
    max_seq_length=MAX_SEQ_LENGTH,
    packing=True,
    seed=SEED,
)

print("\nTraining Configuration:")
print(f"  Epochs: {NUM_TRAIN_EPOCHS}")
print(f"  Batch Size: {BATCH_SIZE}")
print(f"  Learning Rate: {STAGE2_LR}")
print(f"  Max Seq Length: {MAX_SEQ_LENGTH}")

# Create trainer for instruction fine-tuning
stage2_trainer = SFTTrainer(
    model=stage2_model,
    tokenizer=tokenizer,
    train_dataset=formatted_instruction_dataset,
    args=stage2_config,
)

# Train
print("\nStarting Stage 2 training...")
start_time = time.time()
stage2_train_result = stage2_trainer.train()
training_time = time.time() - start_time

print(f"\n✓ Stage 2 Training Complete!")
print(f"Training time: {training_time:.2f}s")
print(f"Final loss: {stage2_train_result.training_loss:.4f}")

# Save adapter
print(f"\nSaving Stage 2 adapter to: {STAGE2_ADAPTER_DIR}")
stage2_model.save_pretrained(STAGE2_ADAPTER_DIR)
tokenizer.save_pretrained(STAGE2_ADAPTER_DIR)

# Save merged model
print(f"Saving Stage 2 merged model to: {STAGE2_MERGED_DIR}")
stage2_model.save_pretrained_merged(
    STAGE2_MERGED_DIR,
    tokenizer,
    save_method="merged_16bit",
)

print("\n✓ Stage 2 artifacts saved")
clear_gpu_memory()

============================================================
STAGE 2: INSTRUCTION-BASED FINE-TUNING
Training on formatted instruction data
============================================================

Loading Stage 1 merged model from: /content/outputs/stage1_non_instruction_merged

Loading model: /content/outputs/stage1_non_instruction_merged
4-bit Quantization (QLoRA): True
==((====))==  Unsloth 2026.7.2: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Unsloth: Will load /content/outputs/stage1_non_instruction_merged as a legacy tokenizer.

Applying LoRA configuration:
  LoRA Rank (r): 16
  LoRA Alpha: 32
  LoRA Dropout: 0.05

Model loaded successfully!
Trainable params: 4,505,600 / 620,111,872
Trainable %: 0.73%

Training Configuration:
  Epochs: 3
  Batch Size: 2
  Learning Rate: 0.0001
  Max Seq Length: 2048
Unsloth: Sample packing skipped (custom data collator detected).

Unsloth: Tokenizing ["text"] (num_proc=5):   0%|          | 0/300 [00:00<?, ? examples/s]

Starting Stage 2 training...

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 300 | Num Epochs = 3 | Total steps = 114
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 4,505,600 of 1,104,553,984 (0.41% trained)

Unsloth: Restored added_tokens_decoder metadata in /content/outputs/stage2_logs/checkpoint-114/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in /content/outputs/stage2_logs/checkpoint-114.
Unsloth: Restored added_tokens_decoder metadata in /content/outputs/stage2_instruction_adapter/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in /content/outputs/stage2_instruction_adapter.

✓ Stage 2 Training Complete!
Training time: 180.86s
Final loss: 0.7912

Saving Stage 2 adapter to: /content/outputs/stage2_instruction_adapter
Saving Stage 2 merged model to: /content/outputs/stage2_instruction_merged
Detected local model directory: /content/outputs/stage1_non_instruction_merged
Copied tokenizer.model from local model directory

Unsloth: Restored added_tokens_decoder metadata in /content/outputs/stage2_instruction_merged/tokenizer_config.json.

Found HuggingFace hub cache directory: /root/.cache/huggingface/hub

Unsloth: Preparing safetensor model files: 100%|██████████| 1/1 [00:16<00:00, 16.47s/it]

Copied model.safetensors from local model directory

Unsloth: Merging weights into 16bit: 100%|██████████| 1/1 [00:33<00:00, 33.87s/it]

Unsloth: Merge process complete. Saved to `/content/outputs/stage2_instruction_merged`

✓ Stage 2 artifacts saved

# Section 9: Inference Functions and Interactive Bot

In [10]:
def generate_response(model, tokenizer, instruction: str, input_text: str = "", max_new_tokens: int = 256) -> str:
    """
    Generate response using the model

    Args:
        model: Fine-tuned model
        tokenizer: Model tokenizer
        instruction: User instruction
        input_text: Optional input context
        max_new_tokens: Maximum tokens to generate

    Returns:
        Generated response
    """
    # Prepare prompt
    FastLanguageModel.for_inference(model)

    prompt = format_instruction_prompt(instruction, input_text)
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=MAX_SEQ_LENGTH).to("cuda")

    # Generate
    with torch.inference_mode():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
            repetition_penalty=1.1,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    # Decode response
    response = tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True).strip()
    return response


def interactive_bot(model, tokenizer, stage_name: str):
    """
    Interactive bot for testing model

    Args:
        model: Fine-tuned model
        tokenizer: Model tokenizer
        stage_name: Name of the model stage
    """
    print(f"\n{'='*60}")
    print(f"Interactive Bot - {stage_name}")
    print(f"{'='*60}")
    print("Enter 'quit' to exit\n")

    test_queries = [
        ("What causes CT Scanner failure scenario?", ""),
        ("What is the function of the Mammography component", ""),
        ("Why is image quality degraded on MRI case?", ""),
    ]

    for instruction, input_text in test_queries:
        print(f"\n[User] Instruction: {instruction}")
        if input_text:
            print(f"[User] Input: {input_text}")

        response = generate_response(model, tokenizer, instruction, input_text)
        print(f"[{stage_name}] Response: {response[:500]}...")
        print("-" * 60)


def batch_generate_responses(model, tokenizer, test_queries: List[Tuple[str, str]]) -> List[str]:
    """
    Generate responses for multiple queries

    Args:
        model: Fine-tuned model
        tokenizer: Model tokenizer
        test_queries: List of (instruction, input) tuples

    Returns:
        List of generated responses
    """
    responses = []
    for instruction, input_text in test_queries:
        response = generate_response(model, tokenizer, instruction, input_text)
        responses.append(response)

    return responses

print("✓ Inference functions defined")

✓ Inference functions defined

# Section 10: Load Models for Inference & Comparison

In [11]:
# Load base model for comparison
print("\n" + "=" * 60)
print("LOADING MODELS FOR INFERENCE")
print("=" * 60)

clear_gpu_memory()

print("\n1. Loading base model...")
base_model, base_tokenizer = FastLanguageModel.from_pretrained(
    model_name=BASE_MODEL,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,
    load_in_4bit=True,
    device_map="cuda:0" # Explicitly place model on GPU 0 to avoid problematic CPU offload validation
)
if base_tokenizer.pad_token is None:
    base_tokenizer.pad_token = base_tokenizer.eos_token
base_tokenizer.padding_side = "right"
print("✓ Base model loaded")

# Load Stage 1 (Non-instruction) model
print("\n2. Loading Stage 1 (Non-instruction) fine-tuned model...")
clear_gpu_memory() # Clear memory before loading next model to be safe
stage1_model, stage1_tokenizer = FastLanguageModel.from_pretrained(
    model_name=STAGE1_MERGED_DIR,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,
    load_in_4bit=True,
    device_map="cuda:0" # Explicitly place model on GPU 0 to avoid problematic CPU offload validation
)
if stage1_tokenizer.pad_token is None:
    stage1_tokenizer.pad_token = stage1_tokenizer.eos_token
stage1_tokenizer.padding_side = "right"
print("✓ Stage 1 model loaded")

# Load Stage 2 (Instruction) model
print("\n3. Loading Stage 2 (Instruction) fine-tuned model...")
clear_gpu_memory() # Clear memory before loading next model to be safe
stage2_model, stage2_tokenizer = FastLanguageModel.from_pretrained(
    model_name=STAGE2_MERGED_DIR,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,
    load_in_4bit=True,
    device_map="cuda:0" # Explicitly place model on GPU 0 to avoid problematic CPU offload validation
)
if stage2_tokenizer.pad_token is None:
    stage2_tokenizer.pad_token = stage2_tokenizer.eos_token
stage2_tokenizer.padding_side = "right"
print("✓ Stage 2 model loaded")

print("\n✓ All models loaded successfully!")

============================================================
LOADING MODELS FOR INFERENCE
============================================================

1. Loading base model...
==((====))==  Unsloth 2026.7.2: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Unsloth: Will load unsloth/tinyllama-bnb-4bit as a legacy tokenizer.

✓ Base model loaded

2. Loading Stage 1 (Non-instruction) fine-tuned model...
==((====))==  Unsloth 2026.7.2: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Unsloth: Will load /content/outputs/stage1_non_instruction_merged as a legacy tokenizer.

✓ Stage 1 model loaded

3. Loading Stage 2 (Instruction) fine-tuned model...
==((====))==  Unsloth 2026.7.2: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Unsloth: Will load /content/outputs/stage2_instruction_merged as a legacy tokenizer.

✓ Stage 2 model loaded

✓ All models loaded successfully!

# Section 11: Merge Non-Instruction and Instruction Fine-Tuned Models

In [12]:
print("\n" + "=" * 60)
print("MERGING MODELS")
print("=" * 60)

print(f"\nNote: Stage 2 model already contains knowledge from Stage 1")
print(f"since it was fine-tuned starting from Stage 1's merged model.")
print(f"\nStage 2 merged model serves as the 'combined' model.")
print(f"Location: {STAGE2_MERGED_DIR}")

# Copy Stage 2 as final merged
import shutil
if os.path.exists(FINAL_MERGED_DIR):
    shutil.rmtree(FINAL_MERGED_DIR)
shutil.copytree(STAGE2_MERGED_DIR, FINAL_MERGED_DIR)

# Load the final merged model
print(f"\nLoading final merged model...")
final_model, final_tokenizer = FastLanguageModel.from_pretrained(
    model_name=FINAL_MERGED_DIR,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,
    load_in_4bit=True,
)
if final_tokenizer.pad_token is None:
    final_tokenizer.pad_token = final_tokenizer.eos_token
final_tokenizer.padding_side = "right"

print("✓ Final merged model (Stage 1 + Stage 2) loaded")
print(f"✓ Saved at: {FINAL_MERGED_DIR}")

============================================================
MERGING MODELS
============================================================

Note: Stage 2 model already contains knowledge from Stage 1
since it was fine-tuned starting from Stage 1's merged model.

Stage 2 merged model serves as the 'combined' model.
Location: /content/outputs/stage2_instruction_merged

Loading final merged model...
==((====))==  Unsloth 2026.7.2: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Unsloth: Will load /content/outputs/final_merged_model as a legacy tokenizer.

✓ Final merged model (Stage 1 + Stage 2) loaded
✓ Saved at: /content/outputs/final_merged_model

# Section 12: Interactive Bot - Test Model Responses

In [ ]:
# test_queries = [
#     ("My CT scanner is producing circular ring artifacts on every scan. What is the most likely cause and what should I inspect first?", ""),
#     ("The CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?", ""),
#     ("How does quantization reduce model size?", ""),
#     ("My MRI system displays a low helium pressure alarm during scanning. What could be causing this?"," "),
#     ("The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?",""),
#     ("The CT gantry will not rotate after startup. Which components should I inspect?",""),
#     ("MRI images contain zipper artifacts. What usually causes this type of artifact?",""),
#     ("The ultrasound image is completely black even though the machine powers on. What are the possible causes?",""),
#     ("What preventive maintenance should be performed on a CT scanner to reduce unexpected failures?",""),
#     ("How can I differentiate between a detector failure and a detector calibration problem in a CT scanner?",""),
#     ("My imaging system repeatedly restarts during operation without displaying any error code. What are the most likely causes?","") ,
# ]

# print("\n" + "=" * 60)
# print("INTERACTIVE BOT TESTING")
# print("=" * 60)

# # Test Base Model
# print("\n" + "-" * 60)
# print("BASE MODEL RESPONSES")
# print("-" * 60)
# base_responses = []
# for instruction, input_text in test_queries:
#     print(f"\nQuery: {instruction}")
#     if input_text:
#         print(f"Input: {input_text}")
#     response = generate_response(base_model, base_tokenizer, instruction, input_text, max_new_tokens=200)
#     base_responses.append(response)
#     print(f"Response: {response[:400]}...")

# clear_gpu_memory()

# # Test Stage 1 Model (Non-Instruction)
# print("\n" + "-" * 60)
# print("STAGE 1 - NON-INSTRUCTION FINE-TUNED MODEL")
# print("-" * 60)
# stage1_responses = []
# for instruction, input_text in test_queries:
#     print(f"\nQuery: {instruction}")
#     if input_text:
#         print(f"Input: {input_text}")
#     response = generate_response(stage1_model, stage1_tokenizer, instruction, input_text, max_new_tokens=200)
#     stage1_responses.append(response)
#     print(f"Response: {response[:400]}...")

# clear_gpu_memory()

# # Test Stage 2 Model (Instruction)
# print("\n" + "-" * 60)
# print("STAGE 2 - INSTRUCTION FINE-TUNED MODEL")
# print("-" * 60)
# stage2_responses = []
# for instruction, input_text in test_queries:
#     print(f"\nQuery: {instruction}")
#     if input_text:
#         print(f"Input: {input_text}")
#     response = generate_response(stage2_model, stage2_tokenizer, instruction, input_text, max_new_tokens=200)
#     stage2_responses.append(response)
#     print(f"Response: {response[:400]}...")

# clear_gpu_memory()

# # Test Final Merged Model
# print("\n" + "-" * 60)
# print("FINAL MERGED MODEL (Stage 1 + Stage 2)")
# print("-" * 60)
# final_responses = []
# for instruction, input_text in test_queries:
#     print(f"\nQuery: {instruction}")
#     if input_text:
#         print(f"Input: {input_text}")
#     response = generate_response(final_model, final_tokenizer, instruction, input_text, max_new_tokens=200)
#     final_responses.append(response)
#     print(f"Response: {response[:400]}...")

# clear_gpu_memory()

# print("\n✓ Interactive bot testing completed")

You can download the CSV file from the file browser on the left-hand side, usually located in the `/content/outputs/` directory named `model_response_comparison.csv`.

# Section 13: Stage 3 Configuration - DPO Training Setup

In [14]:
# ==========================================
# STAGE 3: DPO TRAINING CONFIGURATION
# ==========================================

# Preference Dataset Path (JSONL format)
# Expected format: {"prompt": "...", "chosen": "...", "rejected": "..."}
PREFERENCE_DATASET_JSONL = "/content/Medical_Imaging_DPO_Preference_Dataset.jsonl"  # Upload your JSONL file

# DPO Configuration Parameters
DPO_BETA = 0.1  # Temperature parameter for DPO (controls preference strength)
DPO_GAMMA = 0.0  # Minimum margin between chosen and rejected (0 = no minimum)
STAGE3_LR = 5e-5  # Lower learning rate for alignment training
DPO_EPOCHS = 2  # Usually 1-3 epochs for preference learning

# Stage 3 output directories
STAGE3_ADAPTER_DIR = f"{OUTPUT_DIR}/stage3_dpo_adapter"
STAGE3_MERGED_DIR = f"{OUTPUT_DIR}/stage3_dpo_merged"
STAGE3_FINAL_MERGED_DIR = f"{OUTPUT_DIR}/stage3_dpo_final_merged"

# Create output directories
for dir_path in [STAGE3_ADAPTER_DIR, STAGE3_MERGED_DIR, STAGE3_FINAL_MERGED_DIR]:
    os.makedirs(dir_path, exist_ok=True)

print("=" * 60)
print("STAGE 3: DPO TRAINING CONFIGURATION")
print("=" * 60)
print(f"Preference Dataset: {PREFERENCE_DATASET_JSONL}")
print(f"DPO Beta (preference strength): {DPO_BETA}")
print(f"DPO Learning Rate: {STAGE3_LR}")
print(f"DPO Epochs: {DPO_EPOCHS}")
print(f"✓ Stage 3 configuration ready")

============================================================
STAGE 3: DPO TRAINING CONFIGURATION
============================================================
Preference Dataset: /content/Medical_Imaging_DPO_Preference_Dataset.jsonl
DPO Beta (preference strength): 0.1
DPO Learning Rate: 5e-05
DPO Epochs: 2
✓ Stage 3 configuration ready

# Section 14: Preference Dataset Loading and Formatting Functions

In [15]:
def load_preference_dataset_from_jsonl(jsonl_path: str) -> Dataset:
    """
    Load preference dataset from JSONL file.

    Expected format: {"prompt": "...", "chosen": "...", "rejected": "..."}

    Args:
        jsonl_path: Path to JSONL file with preference pairs

    Returns:
        HuggingFace Dataset with prompt, chosen, rejected columns
    """
    records = []

    try:
        with open(jsonl_path, 'r') as f:
            for line_num, line in enumerate(f, 1):
                if line.strip():
                    try:
                        record = json.loads(line)

                        # Validate required fields
                        required_fields = ['prompt', 'chosen', 'rejected']
                        missing_fields = [f for f in required_fields if f not in record]

                        if missing_fields:
                            print(f"⚠ Line {line_num}: Missing fields {missing_fields}, skipping")
                            continue

                        # Clean and validate data
                        record['prompt'] = str(record['prompt']).strip()
                        record['chosen'] = str(record['chosen']).strip()
                        record['rejected'] = str(record['rejected']).strip()

                        if record['prompt'] and record['chosen'] and record['rejected']:
                            records.append(record)
                        else:
                            print(f"⚠ Line {line_num}: Empty fields detected, skipping")

                    except json.JSONDecodeError as e:
                        print(f"⚠ Line {line_num}: JSON decode error {e}, skipping")
                        continue

    except FileNotFoundError:
        print(f"⚠ Preference dataset not found at {jsonl_path}")
        print("Creating sample preference dataset for demonstration...")

        # Create sample preference dataset
        sample_preferences = [
            {
                "prompt": "Why is image quality degraded on PET-CT case 1?",
                "chosen": "mage degradation may result from calibration errors, detector or probe issues, motion artifacts, electronic noise, or reconstruction problems.\n\nRecommended workflow: confirm the symptom, inspect related components, review alarms, perform diagnostics and calibration, isolate the root cause, replace faulty parts if necessary, and verify normal operation",
                "rejected": "Restart the equipment and ignore any alarms because they are usually not important."
            },
            {
                "prompt": "What preventive maintenance is required for Ultrasound item 2",
                "chosen": "Perform routine cleaning, inspect connectors, verify calibration, check cooling performance, review logs, and replace worn consumables according to maintenance schedules.\n\nRecommended workflow: confirm the symptom, inspect related components, review alarms, perform diagnostics and calibration, isolate the root cause, replace faulty parts if necessary, and verify normal operation.",
                "rejected": "Restart the equipment and ignore any alarms because they are usually not important"
            },
            {
                "prompt": "Why is image quality degraded on X-ray case 2?",
                "chosen": "Image degradation may result from calibration errors, detector or probe issues, motion artifacts, electronic noise, or reconstruction problems.\n\nRecommended workflow: confirm the symptom, inspect related components, review alarms, perform diagnostics and calibration, isolate the root cause, replace faulty parts if necessary, and verify normal operation.",
                "rejected": "Restart the equipment and ignore any alarms because they are usually not important."
            },

        ]

        records = sample_preferences
        print(f"✓ Created sample preference dataset with {len(records)} examples")

    dataset = Dataset.from_list(records)
    print(f"✓ Loaded {len(dataset)} preference examples")

    if len(dataset) > 0:
        print(f"\nSample preference pair:")
        print(f"Prompt: {dataset[0]['prompt'][:100]}...")
        print(f"Chosen: {dataset[0]['chosen'][:100]}...")
        print(f"Rejected: {dataset[0]['rejected'][:100]}...")

    return dataset


def format_preference_dataset_for_dpo(dataset: Dataset) -> Dataset:
    """
    Format preference dataset for DPO training.
    DPO expects: prompt, chosen, rejected fields

    Args:
        dataset: Raw preference dataset

    Returns:
        Formatted dataset ready for DPO training
    """
    def format_dpo_row(row):
        # Format prompt with instruction template
        prompt = row['prompt'].strip()

        # Format chosen and rejected responses
        chosen = row['chosen'].strip()
        rejected = row['rejected'].strip()

        return {
            "prompt": prompt,
            "chosen": chosen,
            "rejected": rejected,
        }

    formatted = dataset.map(format_dpo_row)
    print(f"✓ Formatted {len(formatted)} preference pairs for DPO")

    if len(formatted) > 0:
        print(f"\nFormatted example:")
        print(f"Prompt: {formatted[0]['prompt']}")
        print(f"Chosen: {formatted[0]['chosen'][:150]}...")
        print(f"Rejected: {formatted[0]['rejected'][:150]}...")

    return formatted


print("✓ Preference dataset functions defined")

✓ Preference dataset functions defined

# Section 15: Load and Format Preference Dataset

In [16]:
# Load preference dataset
print("\n" + "=" * 60)
print("LOADING PREFERENCE DATASET")
print("=" * 60)

preference_dataset = load_preference_dataset_from_jsonl(PREFERENCE_DATASET_JSONL)

# Format for DPO training
formatted_preference_dataset = format_preference_dataset_for_dpo(preference_dataset)

print(f"\n✓ Preference dataset ready: {len(formatted_preference_dataset)} pairs")
print(f"Dataset columns: {formatted_preference_dataset.column_names}")

# Split into train and eval if dataset is large enough
if len(formatted_preference_dataset) > 10:
    train_test_split = formatted_preference_dataset.train_test_split(test_size=0.1, seed=SEED)
    dpo_train_dataset = train_test_split['train']
    dpo_eval_dataset = train_test_split['test']
    print(f"Train: {len(dpo_train_dataset)}, Eval: {len(dpo_eval_dataset)}")
else:
    dpo_train_dataset = formatted_preference_dataset
    dpo_eval_dataset = formatted_preference_dataset
    print("⚠ Small dataset - using same data for train and eval")

============================================================
LOADING PREFERENCE DATASET
============================================================
✓ Loaded 300 preference examples

Sample preference pair:
Prompt: ### Instruction:
What is the function of the CT Scanner component 1?

### Response:...
Chosen: The referenced component in the CT Scanner performs its designated operational role and should be in...
Rejected: Restart the equipment and ignore alarms. Continue operation without diagnostics, calibration, inspec...

Map:   0%|          | 0/300 [00:00<?, ? examples/s]

✓ Formatted 300 preference pairs for DPO

Formatted example:
Prompt: ### Instruction:
What is the function of the CT Scanner component 1?

### Response:
Chosen: The referenced component in the CT Scanner performs its designated operational role and should be inspected according to the service manual if abnorma...
Rejected: Restart the equipment and ignore alarms. Continue operation without diagnostics, calibration, inspection, or verification because the issue will usual...

✓ Preference dataset ready: 300 pairs
Dataset columns: ['prompt', 'chosen', 'rejected', 'source_page', 'topic']
Train: 270, Eval: 30

# Section 16: DPO Training Imports and Configuration

In [17]:
# Import DPO trainer
try:
    from trl import DPOTrainer, DPOConfig
    print("✓ DPOTrainer imported successfully")
except ImportError:
    print("⚠ DPOTrainer not found, installing TRL...")
    import subprocess
    import sys
    subprocess.run([sys.executable, '-m', 'pip', 'install', '-U', 'trl'], capture_output=True)
    from trl import DPOTrainer, DPOConfig
    print("✓ DPOTrainer installed and imported")

✓ DPOTrainer imported successfully

# Section 17: Stage 3 - DPO Training

In [18]:
print("\n" + "=" * 60)
print("STAGE 3: DPO PREFERENCE ALIGNMENT TRAINING")
print("=" * 60)

# Load Stage 2 model as reference (SFT model)
clear_gpu_memory()
print(f"\nLoading Stage 2 SFT model as reference...")
sft_model, tokenizer = load_model_with_lora(STAGE2_MERGED_DIR, load_in_4bit=True)

# Configure DPO training
dpo_config = DPOConfig(
    output_dir=f"{OUTPUT_DIR}/stage3_logs",
    num_train_epochs=DPO_EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
    learning_rate=STAGE3_LR,
    warmup_steps=WARMUP_STEPS,
    logging_steps=LOGGING_STEPS,
    save_strategy="steps",
    save_steps=max(500, len(dpo_train_dataset) // 2),
    eval_strategy="steps",
    eval_steps=max(500, len(dpo_train_dataset) // 2),
    report_to="none",
    fp16=not is_bfloat16_supported(),
    bf16=is_bfloat16_supported(),
    optim="adamw_8bit",
    max_length=MAX_SEQ_LENGTH,
    # max_prompt_length=int(MAX_SEQ_LENGTH * 0.5),  # Limit prompt length - Removed due to TypeError
    beta=DPO_BETA,  # Preference strength
    # gamma=DPO_GAMMA,  # Minimum margin - Removed due to TypeError
    loss_type="sigmoid",  # Use sigmoid loss for DPO
    # packing=False,  # Don't pack for DPO (needs proper tokenization) - Removed due to TypeError
    seed=SEED,
)

print("\nDPO Training Configuration:")
print(f"  Epochs: {DPO_EPOCHS}")
print(f"  Batch Size: {BATCH_SIZE}")
print(f"  Learning Rate: {STAGE3_LR}")
print(f"  DPO Beta (strength): {DPO_BETA}")
print(f"  Max Sequence Length: {MAX_SEQ_LENGTH}")
print(f"  Train samples: {len(dpo_train_dataset)}")
print(f"  Eval samples: {len(dpo_eval_dataset)}")

# Create DPO trainer
dpo_trainer = DPOTrainer(
    model=sft_model,
    ref_model=None,  # Will use base model from sft_model
    tokenizer=tokenizer,
    train_dataset=dpo_train_dataset,
    eval_dataset=dpo_eval_dataset,
    args=dpo_config,
)

# Train with DPO
print(
"\nStarting Stage 3 DPO training...")
print("-" * 60)
start_time = time.time()

try:
    dpo_train_result = dpo_trainer.train()
    training_time = time.time() - start_time

    print(f"\n✓ Stage 3 DPO Training Complete!")
    print(f"Training time: {training_time:.2f}s")
    print(f"Final loss: {dpo_train_result.training_loss:.4f}")
except Exception as e:
    print(f"⚠ Training error: {e}")
    print("Attempting to save current state...")
    dpo_trainer.save_model(STAGE3_ADAPTER_DIR)

# Save DPO adapter
print(f"\nSaving Stage 3 DPO adapter to: {STAGE3_ADAPTER_DIR}")
dpo_trainer.model.save_pretrained(STAGE3_ADAPTER_DIR)
tokenizer.save_pretrained(STAGE3_ADAPTER_DIR)

# Save DPO merged model
print(f"Saving Stage 3 DPO merged model to: {STAGE3_MERGED_DIR}")
dpo_trainer.model.save_pretrained_merged(
    STAGE3_MERGED_DIR,
    tokenizer,
    save_method="merged_16bit",
)

print("\n✓ Stage 3 DPO artifacts saved")
clear_gpu_memory()

============================================================
STAGE 3: DPO PREFERENCE ALIGNMENT TRAINING
============================================================

Loading Stage 2 SFT model as reference...

Loading model: /content/outputs/stage2_instruction_merged
4-bit Quantization (QLoRA): True
==((====))==  Unsloth 2026.7.2: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Unsloth: Will load /content/outputs/stage2_instruction_merged as a legacy tokenizer.

Applying LoRA configuration:
  LoRA Rank (r): 16
  LoRA Alpha: 32
  LoRA Dropout: 0.05

Model loaded successfully!
Trainable params: 4,505,600 / 620,111,872
Trainable %: 0.73%

DPO Training Configuration:
  Epochs: 2
  Batch Size: 2
  Learning Rate: 5e-05
  DPO Beta (strength): 0.1
  Max Sequence Length: 2048
  Train samples: 270
  Eval samples: 30

Adding EOS to train dataset (num_proc=2):   0%|          | 0/270 [00:00<?, ? examples/s]

Tokenizing train dataset (num_proc=2):   0%|          | 0/270 [00:00<?, ? examples/s]

Adding EOS to eval dataset (num_proc=2):   0%|          | 0/30 [00:00<?, ? examples/s]

Tokenizing eval dataset (num_proc=2):   0%|          | 0/30 [00:00<?, ? examples/s]

Starting Stage 3 DPO training...
------------------------------------------------------------

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 270 | Num Epochs = 2 | Total steps = 68
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 4,505,600 of 1,109,059,584 (0.41% trained)

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

Unsloth: Restored added_tokens_decoder metadata in /content/outputs/stage3_logs/checkpoint-68/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in /content/outputs/stage3_logs/checkpoint-68.

✓ Stage 3 DPO Training Complete!
Training time: 157.90s
Final loss: 0.6934

Saving Stage 3 DPO adapter to: /content/outputs/stage3_dpo_adapter

Unsloth: Restored added_tokens_decoder metadata in /content/outputs/stage3_dpo_adapter/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in /content/outputs/stage3_dpo_adapter.

Saving Stage 3 DPO merged model to: /content/outputs/stage3_dpo_merged
Detected local model directory: /content/outputs/stage2_instruction_merged
Copied tokenizer.model from local model directory

Unsloth: Restored added_tokens_decoder metadata in /content/outputs/stage3_dpo_merged/tokenizer_config.json.

Found HuggingFace hub cache directory: /root/.cache/huggingface/hub

Unsloth: Preparing safetensor model files: 100%|██████████| 1/1 [01:48<00:00, 108.55s/it]

Copied model.safetensors from local model directory

Unsloth: Merging weights into 16bit: 100%|██████████| 1/1 [02:07<00:00, 127.09s/it]

Unsloth: Merge process complete. Saved to `/content/outputs/stage3_dpo_merged`

✓ Stage 3 DPO artifacts saved

# Section 18: Testing Stage 3 DPO Model (Before Merge)

In [19]:
# Load DPO model for inference
print("\n" + "=" * 60)
print("TESTING STAGE 3 DPO MODEL (Before Merge)")
print("=" * 60)

clear_gpu_memory()

print(f"\nLoading Stage 3 DPO merged model...")
dpo_model, dpo_tokenizer = FastLanguageModel.from_pretrained(
    model_name=STAGE3_MERGED_DIR,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,
    load_in_4bit=True,
)
if dpo_tokenizer.pad_token is None:
    dpo_tokenizer.pad_token = dpo_tokenizer.eos_token
dpo_tokenizer.padding_side = "right"
print("✓ Stage 3 DPO model loaded")

# Test queries from preference dataset
dpo_test_queries = [

    ("My CT scanner is producing circular ring artifacts on every scan. What is the most likely cause and what should I inspect first?", ""),
("The CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?", ""),
("How does quantization reduce model size?", ""),
]

print("\n" + "-" * 60)
print("DPO ALIGNED MODEL - TEST RESPONSES (Before Merge)")
print("-" * 60)

dpo_responses_before_merge = []
for instruction, input_text in dpo_test_queries:
    print(f"\n[Query] {instruction}")
    response = generate_response(dpo_model, dpo_tokenizer, instruction, input_text, max_new_tokens=200)
    dpo_responses_before_merge.append(response)
    print(f"[Response] {response[:400]}...")

clear_gpu_memory()

print("\n✓ DPO model testing complete (before merge)")

============================================================
TESTING STAGE 3 DPO MODEL (Before Merge)
============================================================

Loading Stage 3 DPO merged model...
==((====))==  Unsloth 2026.7.2: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Unsloth: Will load /content/outputs/stage3_dpo_merged as a legacy tokenizer.
Both `max_new_tokens` (=200) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

✓ Stage 3 DPO model loaded

------------------------------------------------------------
DPO ALIGNED MODEL - TEST RESPONSES (Before Merge)
------------------------------------------------------------

[Query] My CT scanner is producing circular ring artifacts on every scan. What is the most likely cause and what should I inspect first?

Both `max_new_tokens` (=200) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Response] Circular ring artifacts are usually caused by misalignment of the CT scanner between the patient and the table. The most likely cause for this problem is misalignment of the patient between the patient table and the patient table. The most likely cause for this problem is misalignment of the patient between the patient table and the patient table. The most likely cause for this problem is misalign...

[Query] The CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?

Both `max_new_tokens` (=200) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Response] The tube overheat alarm was likely caused by an overheated tube, which could be due to either a faulty or improperly calibrated temperature sensor. The temperature sensor is most likely a thermistor, and the tube overheat alarm would indicate that the tube has reached its maximum operating temperature.

### Response:

The tube overheat alarm was likely caused by an overheated tube, which could be ...

[Query] How does quantization reduce model size?
[Response] **Quantization reduces the number of parameters in a neural network.

This results in a smaller, more efficient model.

**Quantization also improves performance by reducing the total number of operations required to train the model.

This leads to better training times and faster models.

**Quantization can be used to create many different types of models.

These include both deep learning models ...

✓ DPO model testing complete (before merge)

# Section 19: Merge DPO with Stage 2 Model

In [20]:
print("\n" + "=" * 60)
print("MERGING STAGE 2 + STAGE 3 (DPO)")
print("=" * 60)

print(f"\nStage 2 (Instruction SFT): {STAGE2_MERGED_DIR}")
print(f"Stage 3 (DPO Alignment):  {STAGE3_MERGED_DIR}")
print(f"\nThe Stage 3 DPO model already contains Stage 2 knowledge")
print(f"since it was trained starting from Stage 2's base model.")

# Copy Stage 3 DPO merged as final merged
import shutil
if os.path.exists(STAGE3_FINAL_MERGED_DIR):
    shutil.rmtree(STAGE3_FINAL_MERGED_DIR)
shutil.copytree(STAGE3_MERGED_DIR, STAGE3_FINAL_MERGED_DIR)

print(f"\n✓ Final merged model created (Stage 2 + DPO)")
print(f"Location: {STAGE3_FINAL_MERGED_DIR}")

# Load the final DPO merged model
clear_gpu_memory()
print(f"\nLoading final DPO-aligned model...")
final_dpo_model, final_dpo_tokenizer = FastLanguageModel.from_pretrained(
    model_name=STAGE3_FINAL_MERGED_DIR,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,
    load_in_4bit=True,
)
if final_dpo_tokenizer.pad_token is None:
    final_dpo_tokenizer.pad_token = final_dpo_tokenizer.eos_token
final_dpo_tokenizer.padding_side = "right"

print("✓ Final DPO-aligned model loaded (Stage 1 + Stage 2 + Stage 3)")
print(f"✓ Saved at: {STAGE3_FINAL_MERGED_DIR}")

============================================================
MERGING STAGE 2 + STAGE 3 (DPO)
============================================================

Stage 2 (Instruction SFT): /content/outputs/stage2_instruction_merged
Stage 3 (DPO Alignment):  /content/outputs/stage3_dpo_merged

The Stage 3 DPO model already contains Stage 2 knowledge
since it was trained starting from Stage 2's base model.

✓ Final merged model created (Stage 2 + DPO)
Location: /content/outputs/stage3_dpo_final_merged

Loading final DPO-aligned model...
==((====))==  Unsloth 2026.7.2: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Unsloth: Will load /content/outputs/stage3_dpo_final_merged as a legacy tokenizer.

✓ Final DPO-aligned model loaded (Stage 1 + Stage 2 + Stage 3)
✓ Saved at: /content/outputs/stage3_dpo_final_merged

# Section 20: Final Testing - Stage 2 vs Stage 3 Comparison

In [21]:
print("\n" + "=" * 60)
print("FINAL TESTING: STAGE 2 (SFT) vs STAGE 3 (DPO)")
print("=" * 60)

# Comprehensive test queries
final_test_queries = [

("My CT scanner is producing circular ring artifacts on every scan. What is the most likely cause and what should I inspect first?", ""),
("The CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?", ""),
("How does quantization reduce model size?", ""),
("My MRI system displays a low helium pressure alarm during scanning. What could be causing this?"," "),
("The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?",""),
("The CT gantry will not rotate after startup. Which components should I inspect?",""),
("MRI images contain zipper artifacts. What usually causes this type of artifact?",""),
("The ultrasound image is completely black even though the machine powers on. What are the possible causes?",""),
("What preventive maintenance should be performed on a CT scanner to reduce unexpected failures?",""),
("How can I differentiate between a detector failure and a detector calibration problem in a CT scanner?",""),
("My imaging system repeatedly restarts during operation without displaying any error code. What are the most likely causes?","") ,
]

# Stage 2 (SFT only) - Load if not already in memory
print("\n" + "-" * 60)
print("STAGE 2: INSTRUCTION-BASED SFT MODEL")
print("-" * 60)

clear_gpu_memory()
stage2_sft_model, stage2_sft_tokenizer = FastLanguageModel.from_pretrained(
    model_name=STAGE2_MERGED_DIR,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,
    load_in_4bit=True,
)
if stage2_sft_tokenizer.pad_token is None:
    stage2_sft_tokenizer.pad_token = stage2_sft_tokenizer.eos_token
stage2_sft_tokenizer.padding_side = "right"

stage2_sft_responses = []
for instruction, input_text in final_test_queries:
    print(f"\n[Query] {instruction}")
    response = generate_response(stage2_sft_model, stage2_sft_tokenizer, instruction, input_text, max_new_tokens=250)
    stage2_sft_responses.append(response)
    print(f"[Stage 2 SFT] {response[:350]}...")

clear_gpu_memory()

# Stage 3 (DPO aligned) responses
print("\n" + "-" * 60)
print("STAGE 3: DPO PREFERENCE-ALIGNED MODEL")
print("-" * 60)

stage3_dpo_responses = []
for instruction, input_text in final_test_queries:
    print(f"\n[Query] {instruction}")
    response = generate_response(final_dpo_model, final_dpo_tokenizer, instruction, input_text, max_new_tokens=250)
    stage3_dpo_responses.append(response)
    print(f"[Stage 3 DPO] {response[:350]}...")

clear_gpu_memory()

print("\n✓ Final testing completed")

# Create comparison table
print("\n" + "=" * 60)
print("COMPARISON TABLE: STAGE 2 vs STAGE 3")
print("=" * 60)

final_comparison_df = pd.DataFrame({
    "Query": [query[0] for query in final_test_queries],
    "Stage 2 (SFT)": stage2_sft_responses,
    "Stage 3 (DPO)": stage3_dpo_responses,
})

final_comparison_df['Preferred Response'] = ''
final_comparison_df['Reason'] = ''

pd.set_option('display.max_colwidth', None)
display(final_comparison_df)

# Export comparison
final_csv_path = f"{OUTPUT_DIR}/stage2_vs_stage3_comparison.csv"
final_comparison_df.to_csv(final_csv_path, index=False)
print(f"\n✓ Final comparison exported to: {final_csv_path}")

print("\n" + "=" * 60)
print("TRAINING PIPELINE COMPLETE!")
print("=" * 60)
print(f"\nArtifacts Location: {OUTPUT_DIR}")
print(f"\nFinal Models:")
print(f"  • Stage 1 (Non-Instruction): {STAGE1_MERGED_DIR}")
print(f"  • Stage 2 (Instruction SFT): {STAGE2_MERGED_DIR}")
print(f"  • Stage 3 (DPO Aligned):     {STAGE3_FINAL_MERGED_DIR}")
print(f"\n✓ Use the final model at: {STAGE3_FINAL_MERGED_DIR}")

============================================================
FINAL TESTING: STAGE 2 (SFT) vs STAGE 3 (DPO)
============================================================

------------------------------------------------------------
STAGE 2: INSTRUCTION-BASED SFT MODEL
------------------------------------------------------------
==((====))==  Unsloth 2026.7.2: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Unsloth: Will load /content/outputs/stage2_instruction_merged as a legacy tokenizer.
Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Query] My CT scanner is producing circular ring artifacts on every scan. What is the most likely cause and what should I inspect first?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] The most likely cause is that the CT scanner has an artifact that is slightly misaligned with the CT axis (CTA) or CT rotator (CTR). The most common artifact is misalignment of the CT axis with the CT rotator. Other artifacts include misalignments of the CTA and CTR, misalignments of the CTA and CTR, misalignments of the CTA and CTR, misalignments ...

[Query] The CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] The tube overheated alarm is caused by a defective tube overheater. The tube overheater overheats when the tube overheat sensor detects that the tube overheat sensor is overheating. The tube overheater overheates because the tube overheater overheaters due to a defect in the tube overheater overheater overheater overheater overheater overheater ove...

[Query] How does quantization reduce model size?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] **Quantization reduces the model size.

**Quantization is a technique for reducing the model size of machine learning models. It is applied when the computational cost and energy consumption of the model are greater than those of the original model, as well as when it is impossible to achieve an acceptable accuracy using the original model. Quantiz...

[Query] My MRI system displays a low helium pressure alarm during scanning. What could be causing this?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] This is not unusual. When the helium pressure sensor detects low helium pressure, it will display an alarm. The alarm indicates that there are low helium pressure conditions. It is not possible for the helium pressure sensor to determine the cause of these low helium pressure conditions. However, the low helium pressure condition alarm is intended ...

[Query] The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] The ultrasound probe was connected, but the system could not detect it. The system should detect the probe automatically when it is connected.

### Response:

The ultrasound probe was connected, but the system could not detect it. The system should detect the probe automatically when it is connected.

### Response:

The ultrasound probe was connect...

[Query] The CT gantry will not rotate after startup. Which components should I inspect?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] * CT gantry rotates when starting, but no gantry components should be inspected.

### Solution:

* The CT gantry rotates after startup....

[Query] MRI images contain zipper artifacts. What usually causes this type of artifact?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] The zipper artifact is caused by the zippers moving when they are pulled. The zipper is moving in two different directions simultaneously, and this creates the zipper artifact.

### Response:

The zipper artifact is caused by the zippers moving when they are pulled. The zipper is moving in two different directions simultaneously, and this creates t...

[Query] The ultrasound image is completely black even though the machine powers on. What are the possible causes?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] A: The ultrasound image is completely black even though the machine powers on. What are the possible causes?

### Response:

A: The ultrasound image is completely black even though the machine powers on. What are the possible causes?

### Response:

A: The ultrasound image is completely black even though the machine powers on. What are the possible...

[Query] What preventive maintenance should be performed on a CT scanner to reduce unexpected failures?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] The CT scanner should be maintained and serviced in accordance with the manufacturer's instructions, but the most common recommended maintenance is performed by the user. (Note that this answer is based upon a review of the answers provided for previous questions.)

### Question 3

A CT scan machine was designed to provide 1000 exams/hr at a cost o...

[Query] How can I differentiate between a detector failure and a detector calibration problem in a CT scanner?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] What does the following response look like in a CT scanner?

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*...

[Query] My imaging system repeatedly restarts during operation without displaying any error code. What are the most likely causes?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] *

*The imaging system is restarted in a loop when it's being used with a monitor.

*The imaging system is restarted in a loop when it's being used with an HDTV monitor.

*The imaging system is restarted in a loop when it's being used with a computer.

*The imaging system is restarted in a loop when it's being used with a television.

*The imaging ...

------------------------------------------------------------
STAGE 3: DPO PREFERENCE-ALIGNED MODEL
------------------------------------------------------------

[Query] My CT scanner is producing circular ring artifacts on every scan. What is the most likely cause and what should I inspect first?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] The CT scanner produces circular ring artifacts (artifacts of multiple rings) due to the following causes:

1. **Fast flipping of the detector matrix**

2. **Low image noise level**

3. **Very small matrix size**

4. **Extremely small detector pitch**

5. **High signal-to-noise ratio**

6. **High image contrast**

7. **High image density**

8. **Hi...

[Query] The CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] A) CT scanner stopped scanning because of a tube overheating alarm.

### Response:

A) CT scanner stopped scanning because of a tube overheating alarm.

### Response:

A) CT scanner stopped scanning because of a tube overheating alarm.

### Response:

A) CT scanner stopped scanning because of a tube overheating alarm.

### Response:

A) CT scanner ...

[Query] How does quantization reduce model size?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] - How does quantization reduce model size?

### Question:

- How does quantization reduce model size?

### Solution:

- How does quantization reduce model size?

### Response:

- How does quantization reduce model size?

### Question:

- How does quantization reduce model size?

### Solution:

- How does quantization reduce model size?

### Respons...

[Query] My MRI system displays a low helium pressure alarm during scanning. What could be causing this?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] The MRI system is displaying an alarm due to a high helium pressure. This indicates that the helium pressure is too high in the MRI system and needs to be lowered.

### Question:

What is the recommended way to lower the helium pressure in the MRI system?

### Response:

There are many ways to lower the helium pressure in the MRI system, such as lo...

[Query] The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] A: The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?

### Response:

A: The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?

### Response:

A: The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot thi...

[Query] The CT gantry will not rotate after startup. Which components should I inspect?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] The CT gantry does not rotate after startup. Which components should I inspect?

### Response:

The CT gantry rotates after startup. Which components should I inspect?

### Response:

The CT gantry rotates after startup. Which components should I inspect?

### Response:

The CT gantry rotates after startup. Which components should I inspect?

### R...

[Query] MRI images contain zipper artifacts. What usually causes this type of artifact?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] It is not clear that the artifact is due to zipper artifacts, because it is not clear how the artifact would be generated by zipper artifacts. It may be due to a difference between the zipper artifacts and the zipper artifacts.

### Discussion:

In some cases, it is possible for zipper artifacts to be caused by zipper artifacts. In other cases, it ...

[Query] The ultrasound image is completely black even though the machine powers on. What are the possible causes?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] The ultrasound image is completely black even though the machine powers on. What are the possible causes?

### Response:

The ultrasound image is completely black even though the machine powers on. What are the possible causes?

### Response:

The ultrasound image is completely black even though the machine powers on. What are the possible causes?
...

[Query] What preventive maintenance should be performed on a CT scanner to reduce unexpected failures?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] It is important to perform preventive maintenance on a CT scanner to reduce unexpected failures.

### Answer:

Preventive maintenance on a CT scanner should include cleaning, lubrication, calibration, inspection and monitoring.

### Response:

Preventive maintenance on a CT scanner should include cleaning, lubrication, calibration, inspection and m...

[Query] How can I differentiate between a detector failure and a detector calibration problem in a CT scanner?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] * Detector failure is when there are no images.
* Detector calibration is when there are images, but they don't look right....

[Query] My imaging system repeatedly restarts during operation without displaying any error code. What are the most likely causes?
[Stage 3 DPO] The system should not restart when operating normally. There may be an error in the imaging system. The imaging system may be damaged and should be replaced.

### Solution:

The imaging system is damaged and should be replaced.

### Response:

The imaging system is damaged and should be replaced.

### Solution:

The imaging system is damaged and sh...

✓ Final testing completed

============================================================
COMPARISON TABLE: STAGE 2 vs STAGE 3
============================================================

,Query,Stage 2 (SFT),Stage 3 (DPO),Preferred Response,Reason
0,My CT scanner is producing circular ring artifacts on every scan. What is the most likely cause and what should I inspect first?,"The most likely cause is that the CT scanner has an artifact that is slightly misaligned with the CT axis (CTA) or CT rotator (CTR). The most common artifact is misalignment of the CT axis with the CT rotator. Other artifacts include misalignments of the CTA and CTR, misalignments of the CTA and CTR, misalignments of the CTA and CTR, misalignments of the CTA and CTR, misalignments of the CTA and CTR, misalignments of the CTA and CTR, misalignments of the CTA and CTR, misalignments of the CTA and CTR, misalignments of the CTA and CTR, misalignments of the CTA and CTR, misalignments of the CTA and CTR, misalignments of the CTA and CTR, misalignments of the CTA and CTR, misalignments of the CTA and CTR, misalignments of the CTA and CTR, misalignments of the CTA and CTR, misalignments of the CTA and CTR, misalignments of the C",The CT scanner produces circular ring artifacts (artifacts of multiple rings) due to the following causes:\n\n1. **Fast flipping of the detector matrix**\n\n2. **Low image noise level**\n\n3. **Very small matrix size**\n\n4. **Extremely small detector pitch**\n\n5. **High signal-to-noise ratio**\n\n6. **High image contrast**\n\n7. **High image density**\n\n8. **High pixel density**\n\n9. **High number of detectors**\n\n10. **High number of slices**\n\n11. **High number of planes**\n\n12. **High number of iterations**\n\n13. **High number of rejection planes**\n\n14. **High number of iterations**\n\n15. **High number of planes**\n\n16. **High number of iterations**\n\n17. **High number of planes**\n\n18. **High number of iterations**\n\n19. **High number of rejection planes**\n\n20,,
1,The CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?,The tube overheated alarm is caused by a defective tube overheater. The tube overheater overheats when the tube overheat sensor detects that the tube overheat sensor is overheating. The tube overheater overheates because the tube overheater overheaters due to a defect in the tube overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater overheater over,A) CT scanner stopped scanning because of a tube overheating alarm.\n\n### Response:\n\nA) CT scanner stopped scanning because of a tube overheating alarm.\n\n### Response:\n\nA) CT scanner stopped scanning because of a tube overheating alarm.\n\n### Response:\n\nA) CT scanner stopped scanning because of a tube overheating alarm.\n\n### Response:\n\nA) CT scanner stopped scanning because of a tube overheating alarm.\n\n### Response:\n\nA) CT scanner stopped scanning because of a tube overheating alarm.\n\n### Response:\n\nA) CT scanner stopped scanning because of a tube overheating alarm.\n\n### Response:\n\nA) CT scanner stopped scanning because of a tube overheating alarm.\n\n### Response:\n\nA) CT scanner stopped scanning because of a tube overheating alarm.\n\n### Response:\n\nA) CT scanner stopped scanning because of a tube overhe,,
2,How does quantization reduce model size?,"**Quantization reduces the model size.\n\n**Quantization is a technique for reducing the model size of machine learning models. It is applied when the computational cost and energy consumption of the model are greater than those of the original model, as well as when it is impossible to achieve an acceptable accuracy using the original model. Quantization is most commonly used to reduce the memory footprint of machine learning models without impacting their performance or accuracy.**\n\n### Response:\n\n**Quantization is a technique for reducing the model size of machine learning models. It is applied when the computational cost and energy consumption of the model are greater than those of the original model, as well as when it is impossible to achieve an acceptable accuracy using the original model. Quantization is most commonly used to reduce the memory footprint of machine learning models without impacting their performance or accuracy.**\n\n### Response:\n\n**Quantization is a technique for reducing the model size of machine learning models. It is applied when the computational cost and energy consumption of the model are greater than those of the original model, as well as when it is impossible to achieve an acceptable accuracy using the original model. Quantization is most commonly used to reduce",- How does quantization reduce model size?\n\n### Question:\n\n- How does quantization reduce model size?\n\n### Solution:\n\n- How does quantization reduce model size?\n\n### Response:\n\n- How does quantization reduce model size?\n\n### Question:\n\n- How does quantization reduce model size?\n\n### Solution:\n\n- How does quantization reduce model size?\n\n### Response:\n\n- How does quantization reduce model size?\n\n### Question:\n\n- How does quantization reduce model size?\n\n### Solution:\n\n- How does quantization reduce model size?\n\n### Response:\n\n- How does quantization reduce model size?\n\n### Question:\n\n- How does quantization reduce model size?\n\n### Solution:\n\n- How does quantization reduce model size?\n\n### Response:\n\n- How does quantization reduce model size?\n\n### Question:\n\n- How does quantization reduce model size?\n\n### Solution:\n\n- How does quantization reduce model size?,,
3,My MRI system displays a low helium pressure alarm during scanning. What could be causing this?,"This is not unusual. When the helium pressure sensor detects low helium pressure, it will display an alarm. The alarm indicates that there are low helium pressure conditions. It is not possible for the helium pressure sensor to determine the cause of these low helium pressure conditions. However, the low helium pressure condition alarm is intended to alert you to the existence of a low helium pressure condition. The low helium pressure condition alarm should also notify you about any actions that need to be taken in response to the low helium pressure condition. You should take action to correct the low helium pressure condition. The low helium pressure condition alarm should also notify you about any actions that have been taken in response to the low helium pressure condition. You can also view the history of the low helium pressure condition alarm and review the results from previous low helium pressure condition alarms.\n\n### Summary\n\nIn this chapter, you learned how to troubleshoot a low helium pressure condition using the MRI System Status dialog box. In the next chapter, you will learn how to troubleshoot a low helium pressure condition using the MRI System Status dialog box.\n\n## Trou","The MRI system is displaying an alarm due to a high helium pressure. This indicates that the helium pressure is too high in the MRI system and needs to be lowered.\n\n### Question:\n\nWhat is the recommended way to lower the helium pressure in the MRI system?\n\n### Response:\n\nThere are many ways to lower the helium pressure in the MRI system, such as lowering the helium pressure by changing the helium pressure control valve or by adding a valve.\n\n### Question:\n\nWhat should you do if you encounter a low helium pressure alarm during scanning?\n\n### Response:\n\nIf you experience a low helium pressure alarm during scanning, it means that the helium pressure is too high in the MRI system and needs to be lowered. Therefore, you should check the helium pressure control valve and change the helium pressure control valve.\n\n### Question:\n\nHow can you determine if the helium pressure control valve is broken?\n\n### Response:\n\nYou can determine if the helium pressure control valve is broken by checking the hel",,
4,"The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?","The ultrasound probe was connected, but the system could not detect it. The system should detect the probe automatically when it is connected.\n\n### Response:\n\nThe ultrasound probe was connected, but the system could not detect it. The system should detect the probe automatically when it is connected.\n\n### Response:\n\nThe ultrasound probe was connected, but the system could not detect it. The system should detect the probe automatically when it is connected.\n\n### Response:\n\nThe ultrasound probe was connected, but the system could not detect it. The system should detect the probe automatically when it is connected.\n\n### Response:\n\nThe ultrasound probe was connected, but the system could not detect it. The system should detect the probe automatically when it is connected.\n\n### Response:\n\nThe ultrasound probe was connected, but the system could not detect it. The system should detect the probe automatically when it is connected.\n\n### Response:\n\nThe ultrasound probe was connected, but the system could not detect it. The system should detect","A: The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?\n\n### Response:\n\nA: The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?\n\n### Response:\n\nA: The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?\n\n### Response:\n\nA: The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?\n\n### Response:\n\nA: The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?\n\n### Response:\n\nA: The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?\n\n### Response:\n\nA: The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?\n\n### Response:\n\nA: The ul",,
5,The CT gantry will not rotate after startup. Which components should I inspect?,"* CT gantry rotates when starting, but no gantry components should be inspected.\n\n### Solution:\n\n* The CT gantry rotates after startup.",The CT gantry does not rotate after startup. Which components should I inspect?\n\n### Response:\n\nThe CT gantry rotates after startup. Which components should I inspect?\n\n### Response:\n\nThe CT gantry rotates after startup. Which components should I inspect?\n\n### Response:\n\nThe CT gantry rotates after startup. Which components should I inspect?\n\n### Response:\n\nThe CT gantry rotates after startup. Which components should I inspect?\n\n### Response:\n\nThe CT gantry rotates after startup. Which components should I inspect?\n\n### Response:\n\nThe CT gantry rotates after startup. Which components should I inspect?\n\n### Response:\n\nThe CT gantry rotates after startup. Which components should I inspect?\n\n### Response:\n\nThe CT gantry rotates after startup. Which components should I inspect?\n\n### Response:\n\nThe CT gantry rotates after startup. Which components should I inspect?\n\n### Response:\n\nThe CT gantry rotates after startup. Which components should I inspect?\n\n##,,
6,MRI images contain zipper artifacts. What usually causes this type of artifact?,"The zipper artifact is caused by the zippers moving when they are pulled. The zipper is moving in two different directions simultaneously, and this creates the zipper artifact.\n\n### Response:\n\nThe zipper artifact is caused by the zippers moving when they are pulled. The zipper is moving in two different directions simultaneously, and this creates the zipper artifact.\n\n### Response:\n\nThe zipper artifact is caused by the zippers moving when they are pulled. The zipper is moving in two different directions simultaneously, and this creates the zipper artifact.\n\n### Response:\n\nThe zipper artifact is caused by the zippers moving when they are pulled. The zipper is moving in two different directions simultaneously, and this creates the zipper artifact.\n\n### Response:\n\nThe zipper artifact is caused by the zippers moving when they are pulled. The zipper is moving in two different directions simultaneously, and this creates the zipper artifact.\n\n### Response:\n\nThe zipper artifact is caused by the zippers moving when","It is not clear that the artifact is due to zipper artifacts, because it is not clear how the artifact would be generated by zipper artifacts. It may be due to a difference between the zipper artifacts and the zipper artifacts.\n\n### Discussion:\n\nIn some cases, it is possible for zipper artifacts to be caused by zipper artifacts. In other cases, it is not possible for zipper artifacts to be caused by zipper artifacts. In still other cases, it is not clear whether the artifact is caused by zipper artifacts or caused by another type of artifact.\n\n### Examples:\n\n**Examples 1 through 3:** Zipper artifacts are not caused by zipper artifacts in Examples 1 through 3. Zipper artifacts are caused by zipper artifacts in Example 4. Zipper artifacts are caused by zipper artifacts in Example 5. Zipper artifacts are caused by zipper artifacts in Example 6. Zipper artifacts are caused by zipper artifact",,
7,The ultrasound image is completely black even though the machine powers on. What are the possible causes?,A: The ultrasound image is completely black even though the machine powers on. What are the possible causes?\n\n### Response:\n\nA: The ultrasound image is completely black even though the machine powers on. What are the possible causes?\n\n### Response:\n\nA: The ultrasound image is completely black even though the machine powers on. What are the possible causes?\n\n### Response:\n\nA: The ultrasound image is completely black even though the machine powers on. What are the possible causes?\n\n### Response:\n\nA: The ultrasound image is completely black even though the machine powers on. What are the possible causes?\n\n### Response:\n\nA: The ultrasound image is completely black even though the machine powers on. What are the possible causes?\n\n### Response:\n\nA: The ultrasound image is completely black even though the machine powers on. What are the possible causes?\n\n### Response:\n\nA: The ultrasound image is completely black even though the machine powers on. What are the possible causes?\n\n### Response:\n\nA,The ultrasound image is completely black even though the machine powers on. What are the possible causes?\n\n### Response:\n\nThe ultrasound image is completely black even though the machine powers on. What are the possible causes?\n\n### Response:\n\nThe ultrasound image is completely black even though the machine powers on. What are the possible causes?\n\n### Response:\n\nThe ultrasound image is completely black even though the machine powers on. What are the possible causes?\n\n### Response:\n\nThe ultrasound image is completely black even though the machine powers on. What are the possible causes?\n\n### Response:\n\nThe ultrasound image is completely black even though the machine powers on. What are the possible causes?\n\n### Response:\n\nThe ultrasound image is completely black even though the machine powers on. What are the possible causes?\n\n### Response:\n\nThe ultrasound image is completely black even though the machine powers on. What are the possible causes?\n\n### Response:\n\nThe ultrasound image is completely black even though the machine powers on. What are,,
8,What preventive maintenance should be performed on a CT scanner to reduce unexpected failures?,"The CT scanner should be maintained and serviced in accordance with the manufacturer's instructions, but the most common recommended maintenance is performed by the user. (Note that this answer is based upon a review of the answers provided for previous questions.)\n\n### Question 3\n\nA CT scan machine was designed to provide 1000 exams/hr at a cost of $1500/exam. The machine is scheduled to last 2 years at which time it will need to be replaced with a new machine. What is the cost per exam in today's dollars?\n\n### Response:\n\nThis question can be answered using the cost per exam in today's dollars. A CT scan machine costs $1500/exam. Therefore, if you do the math, the cost per exam is $1500/exam or $87.96 per hour. This amount is also included in the cost of the CT machine. Therefore, the cost per exam is $87.96/hour. If you do the math again, the cost per exam is $87.96 x 2 = $224","It is important to perform preventive maintenance on a CT scanner to reduce unexpected failures.\n\n### Answer:\n\nPreventive maintenance on a CT scanner should include cleaning, lubrication, calibration, inspection and monitoring.\n\n### Response:\n\nPreventive maintenance on a CT scanner should include cleaning, lubrication, calibration, inspection and monitoring.\n\n### Answer:\n\nPreventive maintenance on a CT scanner should include cleaning, lubrication, calibration, inspection and monitoring.\n\n### Response:\n\nPreventive maintenance on a CT scanner should include cleaning, lubrication, calibration, inspection and monitoring.\n\n### Answer:\n\nPreventive maintenance on a CT scanner should include cleaning, lubrication, calibration, inspection and monitoring.\n\n### Response:\n\nPreventive maintenance on a CT scanner should include cleaning, lubrication, calibration, inspection and monitoring.\n\n### Answer:\n\nPreventive maintenance on a CT scanner should include cleaning, lubrication,",,
9,How can I differentiate between a detector failure and a detector calibration problem in a CT scanner?,What does the following response look like in a CT scanner?\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*,"* Detector failure is when there are no images.\n* Detector calibration is when there are images, but they don't look right.",,

✓ Final comparison exported to: /content/outputs/stage2_vs_stage3_comparison.csv

============================================================
TRAINING PIPELINE COMPLETE!
============================================================

Artifacts Location: /content/outputs

Final Models:
  • Stage 1 (Non-Instruction): /content/outputs/stage1_non_instruction_merged
  • Stage 2 (Instruction SFT): /content/outputs/stage2_instruction_merged
  • Stage 3 (DPO Aligned):     /content/outputs/stage3_dpo_final_merged

✓ Use the final model at: /content/outputs/stage3_dpo_final_merged

In [22]:
# Define comprehensive test queries
final_test_queries = [
("My CT scanner is producing circular ring artifacts on every scan. What is the most likely cause and what should I inspect first?", ""),
("The CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?", ""),
("How does quantization reduce model size?", ""),
("My MRI system displays a low helium pressure alarm during scanning. What could be causing this?"," "),
("The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?",""),
("The CT gantry will not rotate after startup. Which components should I inspect?",""),
("MRI images contain zipper artifacts. What usually causes this type of artifact?",""),
("The ultrasound image is completely black even though the machine powers on. What are the possible causes?",""),
("What preventive maintenance should be performed on a CT scanner to reduce unexpected failures?",""),
("How can I differentiate between a detector failure and a detector calibration problem in a CT scanner?",""),
("My imaging system repeatedly restarts during operation without displaying any error code. What are the most likely causes?","") ,
]

print("\n" + "=" * 60)
print("FINAL MODEL COMPARISON: Base vs Stage 2 vs Stage 3")
print("=" * 60)

# --- Get responses from Base Model ---
print("\n" + "-" * 60)
print("BASE MODEL RESPONSES")
print("-" * 60)
base_responses = []
for instruction, input_text in final_test_queries:
    print(f"\n[Query] {instruction}")
    response = generate_response(base_model, base_tokenizer, instruction, input_text, max_new_tokens=250)
    base_responses.append(response)
    print(f"[Base Model] {response[:350]}...")
clear_gpu_memory()

# --- Get responses from Stage 2 (Instruction SFT) Model ---
print("\n" + "-" * 60)
print("STAGE 2: INSTRUCTION-BASED SFT MODEL RESPONSES")
print("-" * 60)
stage2_sft_responses = []
for instruction, input_text in final_test_queries:
    print(f"\n[Query] {instruction}")
    # stage2_sft_model and stage2_sft_tokenizer are loaded in a previous cell
    response = generate_response(stage2_sft_model, stage2_sft_tokenizer, instruction, input_text, max_new_tokens=250)
    stage2_sft_responses.append(response)
    print(f"[Stage 2 SFT] {response[:350]}...")
clear_gpu_memory()

# --- Get responses from Stage 3 (DPO aligned) Model ---
print("\n" + "-" * 60)
print("STAGE 3: DPO PREFERENCE-ALIGNED MODEL RESPONSES")
print("-" * 60)
stage3_dpo_responses = []
for instruction, input_text in final_test_queries:
    print(f"\n[Query] {instruction}")
    # final_dpo_model and final_dpo_tokenizer are loaded in a previous cell
    response = generate_response(final_dpo_model, final_dpo_tokenizer, instruction, input_text, max_new_tokens=250)
    stage3_dpo_responses.append(response)
    print(f"[Stage 3 DPO] {response[:350]}...")
clear_gpu_memory()

print("\n✓ All model responses collected")

# --- Create and display comparison table ---
print("\n" + "=" * 60)
print("COMPARISON TABLE: Base vs Stage 2 vs Stage 3")
print("=" * 60)

final_comparison_df = pd.DataFrame({
    "Query": [query[0] for query in final_test_queries],
    "Base Model": base_responses,
    "Stage 2 (SFT)": stage2_sft_responses,
    "Stage 3 (DPO)": stage3_dpo_responses,
})

pd.set_option('display.max_colwidth', None)
display(final_comparison_df)

# --- Export comparison to CSV ---
final_csv_path = f"{OUTPUT_DIR}/model_response_comparison.csv"
final_comparison_df.to_csv(final_csv_path, index=False)
print(f"\n✓ Comparison exported to: {final_csv_path}")

print("\n" + "=" * 60)
print("COMPARISON COMPLETE!")
print("=" * 60)

============================================================
FINAL MODEL COMPARISON: Base vs Stage 2 vs Stage 3
============================================================

------------------------------------------------------------
BASE MODEL RESPONSES
------------------------------------------------------------

[Query] My CT scanner is producing circular ring artifacts on every scan. What is the most likely cause and what should I inspect first?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Base Model] The most likely cause of this artifact is that you are using a very low resolution (1024×768) and that your scan was performed at a high speed (5000 Hz).
This artifact is due to the high sampling frequency, which causes aliasing in the Fourier domain, resulting in artifacts being produced when the phase and amplitude of a waveform are sampled at di...

[Query] The CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Base Model] - The CT scanner was stopped by the tube overheating alarm.
- The tube overheated due to an improperly functioning heater element.
- An improperly functioning heater element caused the tube overheating alarm.
- An improperly functioning heater element caused the tube overheating alarm to trigger....

[Query] How does quantization reduce model size?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Base Model] > We need to find a way to quantize the model in such a way that it reduces the number of parameters.


### How?

We have two approaches here:

* Compressing the weights before quantizing them. This is done by using compression libraries like Pytorch's [TFCompression](https://github.com/tensorflow/models/blob/master/weights/README.md).
* Quantizing...

[Query] My MRI system displays a low helium pressure alarm during scanning. What could be causing this?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Base Model] The alarm is due to the high helium pressure inside of the system. When the pressure gets too high, the helium will leak out of the system and into your body. The system will have to shut down for cleaning, which can cause you to lose some of your scan data.

### Answer:
Helium is used in the MRI system as a contrast agent because it has a high aff...

[Query] The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Base Model] In order to troubleshoot a probe detection issue, you will need to run a software diagnostic on the device. To do so, go into the "Software" tab of your "Device Management" section in the Device Console and select "Troubleshoot". Here, you can then select the "Probe Detection" option and click "Continue". This will bring up a screen where you can s...

[Query] The CT gantry will not rotate after startup. Which components should I inspect?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Base Model] The CT gantry will not rotate after startup, which components should I inspect?

- The motor shaft bearing.
- The drive shaft bearing.
- The drive motor.
- The drive motor bearing.
- The control system.
- The drive shaft.
- The drive shaft bearing.
- The drive motor bracket.
- The drive motor bearing.
- The drive motor bearing support.
- The motor ...

[Query] MRI images contain zipper artifacts. What usually causes this type of artifact?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Base Model] MRI images contain zipper artifacts. The artifact is a result of the fact that MRI scanners generate images by using a continuous x-ray beam, which is directed to the patient's body through an open endoscope. This endoscope is also called the gantry. Because the gantry moves during the scan, it can pass through the patient's body at any given time....

[Query] The ultrasound image is completely black even though the machine powers on. What are the possible causes?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Base Model] The ultrasound image is completely black even though the machine is powered on. This means that the ultrasonic waves have not propagated through the entire machine, and it is time to take a break and let them do their job. The machine will restart automatically when the ultrasonic waves reach an acceptable threshold value.

This is the most common ...

[Query] What preventive maintenance should be performed on a CT scanner to reduce unexpected failures?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Base Model] - Calibrate the machine frequently.
- Clean the coils with a wet cloth once or twice a day.
- Make sure that the ionizing radiation is not being absorbed by the body....

[Query] How can I differentiate between a detector failure and a detector calibration problem in a CT scanner?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Base Model] The response is the difference in signal intensity (SI) measured at each slice of a scan.

I would like to differentiate between a defective detector and a defective scanning procedure, e.g. due to an incorrect detector position or a misalignment of the detector. Is there any way that I could differentiate these conditions?

* * *

* *

* *

* * *...

[Query] My imaging system repeatedly restarts during operation without displaying any error code. What are the most likely causes?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Base Model] Inspect the system for obvious signs of damage, and check the power supply and its connections. If you find nothing, then inspect the system's control board and make sure that there is no open wiring between the system and the power supply.

### Response:

Check all of your sensors and actuators. Make sure they are properly connected to the system'...

------------------------------------------------------------
STAGE 2: INSTRUCTION-BASED SFT MODEL RESPONSES
------------------------------------------------------------

[Query] My CT scanner is producing circular ring artifacts on every scan. What is the most likely cause and what should I inspect first?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] *

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*

*...

[Query] The CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] The CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?

### Response:

The CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?

### Response:

The CT scanner stopped scanning because of a tube overheating alarm. What components are likely resp...

[Query] How does quantization reduce model size?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] - Quantization reduces the number of parameters in the network.
- This is because the number of parameters in the network can be reduced using a smaller number of bits to represent each parameter.
- As a result, the size of the network and the number of parameters are reduced.

### Response:

- Quantization reduces the number of parameters in the n...

[Query] My MRI system displays a low helium pressure alarm during scanning. What could be causing this?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] The helium pressure alarm is triggered when the helium pressure inside the scanner exceeds a certain level. This happens very rarely, but if it does happen, it indicates that the helium pressure inside the scanner has been reduced below a certain level.

### Question:

How can I get my MRI system to display a high helium pressure alarm when scannin...

[Query] The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] The ultrasound probe was not detected because the system does not know that it is attached to the ultrasound machine. You can use the following steps to troubleshoot this issue:

- **Step 1:** Connect the probe using a USB cable and reconnect it to the system. This will allow you to view the probe's status in the system.
- **Step 2:** Check to see ...

[Query] The CT gantry will not rotate after startup. Which components should I inspect?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] The CT gantry rotates after startup. The CT gantry does not rotate after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT ga...

[Query] MRI images contain zipper artifacts. What usually causes this type of artifact?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] This artifact is not due to an MRI scan; it is a result of the magnetic field strength in the MRI scanner. The magnetic field strength in the MRI scanner is much higher than the strength of the earth's magnetic field, so the zipper artifact appears when the magnet is turned on.

### Question:

Which type of artifact is caused by an MRI scan and whi...

[Query] The ultrasound image is completely black even though the machine powers on. What are the possible causes?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] The ultrasound image is completely black even though the machine powers on. What are the possible causes?

### Response:

The ultrasound image is completely black even though the machine powers on. What are the possible causes?

### Response:

The ultrasound image is completely black even though the machine powers on. What are the possible causes?
...

[Query] What preventive maintenance should be performed on a CT scanner to reduce unexpected failures?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] The most important preventive maintenance is the replacement of the x-ray tubes. (1) The tubes should be replaced every five years, and (2) the tubes should be replaced when they have more than 80% of their useful life remaining.

### Answers:

**(1)** The tubes should be replaced every five years, and (2) the tubes should be replaced when they hav...

[Query] How can I differentiate between a detector failure and a detector calibration problem in a CT scanner?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] 1.  The detector calibration procedure is used to correct the detector response function, which is the relationship between the detector response and the input signal.
2.  Calibration is performed using the calibration procedure.
3.  A detector failure occurs when there is an error or anomaly in the detector calibration procedure.
4.  A detector fa...

[Query] My imaging system repeatedly restarts during operation without displaying any error code. What are the most likely causes?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 2 SFT] - Imaging system repeatedly restarts during operation without displaying any error code. What are the most likely causes?

### Response:

- Imaging system repeatedly restarts during operation without displaying any error code. What are the most likely causes?

### Response:

- Imaging system repeatedly restarts during operation without displaying a...

------------------------------------------------------------
STAGE 3: DPO PREFERENCE-ALIGNED MODEL RESPONSES
------------------------------------------------------------

[Query] My CT scanner is producing circular ring artifacts on every scan. What is the most likely cause and what should I inspect first?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] - The CT scanner has a limited range of motion in its rotary arm, so any rotation beyond that point will produce the artifact. Rotation past 90 degrees will produce artifacts as well.
- The CT scanner's rotational arm is not perfectly aligned with the patient's body, which causes some movement in the patient's body during rotation. This motion will...

[Query] The CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] * *

**Answer:** The CT scanner is most likely overheated by the tube overheating alarm, and the tube is most likely overheated by the tube overheating alarm.

### Response:

* *

**Answer:** The CT scanner is overheated by the tube overheating alarm, and the tube is overheated by the tube overheating alarm.

### Response:

* *

**Answer:** The CT ...

[Query] How does quantization reduce model size?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] ### Response:

### Response:

### Response:

### Response:

### Response:

### Response:

### Response:

### Response:

### Response:

### Response:

### Response:

### Response:

### Response:

### Response:

### Response:

### Response:

### Response:

### Response:

### Response:

### Response:

### Response:

### Response:

### Response:

### R...

[Query] My MRI system displays a low helium pressure alarm during scanning. What could be causing this?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] The helium pressure sensor is broken and will not detect the helium pressure during scanning.

### Solution:

Check the helium pressure sensor for a leak.

### Response:

The helium pressure sensor is broken and will not detect the helium pressure during scanning.

### Solution:

Check the helium pressure sensor for a leak.

### Response:

The heli...

[Query] The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] To troubleshoot this issue, you can connect the ultrasound probe to another device and check whether the system detects it or not. You may also try disconnecting the ultrasound probe from the system and then reconnecting it again to see if the system detects it or not. If the system still does not detect the ultrasound probe, you can try disabling ...

[Query] The CT gantry will not rotate after startup. Which components should I inspect?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] - The CT gantry does rotate after startup and the CT gantry will rotate after startup. Which components should I inspect?
- The CT gantry does rotate after startup and the CT gantry will rotate after startup. Which components should I inspect?
- The CT gantry does rotate after startup and the CT gantry will rotate after startup. Which components sh...

[Query] MRI images contain zipper artifacts. What usually causes this type of artifact?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] * **Zooms:**
  * **MRI images:**
    * **MRI images contain zipper artifacts. What usually causes this type of artifact?**
* **Zooms:**
  * **MRI images:**
    * **MRI images contain zipper artifacts. What usually causes this type of artifact?**

### Response:

* **Zooms:**
  * **MRI images:**
    * **MRI images contain zipper artifacts. What usual...

[Query] The ultrasound image is completely black even though the machine powers on. What are the possible causes?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] The ultrasound image is completely black even though the machine powers on. What are the possible causes?


### Response:

The ultrasound image is completely black even though the machine powers on. What are the possible causes?


### Response:

The ultrasound image is completely black even though the machine powers on. What are the possible causes...

[Query] What preventive maintenance should be performed on a CT scanner to reduce unexpected failures?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] A CT scanner should be inspected and serviced as needed.

### Response:

A CT scanner should be inspected, cleaned, and serviced as needed.

### Response:

A CT scanner should be inspected, cleaned, and serviced as needed.

### Response:

A CT scanner should be inspected, cleaned, and serviced as needed.

### Response:

A CT scanner should be inspe...

[Query] How can I differentiate between a detector failure and a detector calibration problem in a CT scanner?

Both `max_new_tokens` (=250) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Stage 3 DPO] What are the possible reasons why the detector could fail in a CT scanner?

### Response:

What are the possible reasons why the detector calibration could fail in a CT scanner?

### Response:

What are the possible reasons why the detector could fail to operate properly in a CT scanner?

### Response:

What are the possible reasons why the detecto...

[Query] My imaging system repeatedly restarts during operation without displaying any error code. What are the most likely causes?
[Stage 3 DPO] The imaging system restarts in response to a power failure or due to other external causes, such as overheating, overload, or a malfunction of the imaging system components. The imaging system does not provide any warning or indication that the imaging system is restarting. The imaging system restarts in response to a power failure or due to other ...

✓ All model responses collected

============================================================
COMPARISON TABLE: Base vs Stage 2 vs Stage 3
============================================================

,Query,Base Model,Stage 2 (SFT),Stage 3 (DPO)
0,My CT scanner is producing circular ring artifacts on every scan. What is the most likely cause and what should I inspect first?,"The most likely cause of this artifact is that you are using a very low resolution (1024×768) and that your scan was performed at a high speed (5000 Hz).\nThis artifact is due to the high sampling frequency, which causes aliasing in the Fourier domain, resulting in artifacts being produced when the phase and amplitude of a waveform are sampled at different frequencies.",*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*,"- The CT scanner has a limited range of motion in its rotary arm, so any rotation beyond that point will produce the artifact. Rotation past 90 degrees will produce artifacts as well.\n- The CT scanner's rotational arm is not perfectly aligned with the patient's body, which causes some movement in the patient's body during rotation. This motion will produce the artifact.\n- The CT scanner's rotating arm is not perfectly aligned with the patient's body, causing some movement in the patient's body during rotation. This motion will also produce the artifact.\n- The CT scanner's rotating arm is not perfectly aligned with the patient's body, causing some movement in the patient's body during rotation. This motion will also produce the artifact.\n- The CT scanner's rotating arm is not perfectly aligned with the patient's body, causing some movement in the patient's body during rotation. This motion will produce the artifact.\n- The CT scanner's rotating arm is not perfectly aligned with the patient's body, causing some movement in the patient's body during rotation. This motion will also produce the"
1,The CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?,- The CT scanner was stopped by the tube overheating alarm.\n- The tube overheated due to an improperly functioning heater element.\n- An improperly functioning heater element caused the tube overheating alarm.\n- An improperly functioning heater element caused the tube overheating alarm to trigger.,The CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?\n\n### Response:\n\nThe CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?\n\n### Response:\n\nThe CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?\n\n### Response:\n\nThe CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?\n\n### Response:\n\nThe CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?\n\n### Response:\n\nThe CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?\n\n### Response:\n\nThe CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?\n\n### Response:\n\nThe CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?\n\n### Response:\n\nThe,"* *\n\n**Answer:** The CT scanner is most likely overheated by the tube overheating alarm, and the tube is most likely overheated by the tube overheating alarm.\n\n### Response:\n\n* *\n\n**Answer:** The CT scanner is overheated by the tube overheating alarm, and the tube is overheated by the tube overheating alarm.\n\n### Response:\n\n* *\n\n**Answer:** The CT scanner is most likely overheated by the tube overheating alarm, and the tube is most likely overheated by the tube overheating alarm.\n\n### Response:\n\n* *\n\n**Answer:** The CT scanner is most likely overheated by the tube overheating alarm, and the tube is most likely overheated by the tube overheating alarm.\n\n### Response:\n\n* *\n\n**Answer:** The CT scanner is overheated by the tube overheating alarm, and the tube is most likely overheated by the"
2,How does quantization reduce model size?,"> We need to find a way to quantize the model in such a way that it reduces the number of parameters.\n\n\n### How?\n\nWe have two approaches here:\n\n* Compressing the weights before quantizing them. This is done by using compression libraries like Pytorch's [TFCompression](https://github.com/tensorflow/models/blob/master/weights/README.md).\n* Quantizing the weights in an efficient way, either by using a specialized library or a simple approach.","- Quantization reduces the number of parameters in the network.\n- This is because the number of parameters in the network can be reduced using a smaller number of bits to represent each parameter.\n- As a result, the size of the network and the number of parameters are reduced.\n\n### Response:\n\n- Quantization reduces the number of parameters in the network.\n- This is because the number of parameters in the network can be reduced using a smaller number of bits to represent each parameter.\n- As a result, the size of the network and the number of parameters are reduced.\n\n### Response:\n\n- Quantization reduces the number of parameters in the network.\n- This is because the number of parameters in the network can be reduced using a smaller number of bits to represent each parameter.\n- As a result, the size of the network and the number of parameters are reduced.\n\n### Response:\n\n- Quantization reduces the number of parameters in the network.\n- This is because the number of parameters in the network can be reduced using a smaller number of bits to represent each parameter.\n- As a result, the size of the network and the number of parameters",### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response:\n\n### Response
3,My MRI system displays a low helium pressure alarm during scanning. What could be causing this?,"The alarm is due to the high helium pressure inside of the system. When the pressure gets too high, the helium will leak out of the system and into your body. The system will have to shut down for cleaning, which can cause you to lose some of your scan data.\n\n### Answer:\nHelium is used in the MRI system as a contrast agent because it has a high affinity for iron atoms, which are found in the brain. This affinity makes helium useful for scans of the brain that involve iron, such as functional imaging (fMRI), structural imaging (SWISS-MET), diffusion tensor imaging (DTI), and perfusion imaging (perfusion SPECT).\n\nHelium is also used in MRI systems as an ionization source when the system is in use. This helps ionize atoms in the MRI system, so they do not interfere with the signals being acquired by the magnet coils.\n\n### Solution:\nWhen the pressure exceeds 0.1 psi, the MRI system can emit a low helium pressure alarm. If the pressure goes above 2 psi","The helium pressure alarm is triggered when the helium pressure inside the scanner exceeds a certain level. This happens very rarely, but if it does happen, it indicates that the helium pressure inside the scanner has been reduced below a certain level.\n\n### Question:\n\nHow can I get my MRI system to display a high helium pressure alarm when scanning?\n\n\n### Response:\n\nYou can turn on the high helium pressure alarm by setting the high helium pressure alarms property of the MRI system to true.\n\n### Question:\n\nHow can I turn off the high helium pressure alarm when scanning?\n\n\n### Response:\n\nYou can turn off the high helium pressure alarm by setting the high helium pressure alarms property of the MRI system to false.\n\n### Question:\n\nWhat are the consequences of turning off the high helium pressure alarm when scanning?\n\n\n### Response:\n\nTurning off the high helium pressure alarm while scanning will not affect any other properties of the MRI system, such as the high helium pressure alarms property or",The helium pressure sensor is broken and will not detect the helium pressure during scanning.\n\n### Solution:\n\nCheck the helium pressure sensor for a leak.\n\n### Response:\n\nThe helium pressure sensor is broken and will not detect the helium pressure during scanning.\n\n### Solution:\n\nCheck the helium pressure sensor for a leak.\n\n### Response:\n\nThe helium pressure sensor is broken and will not detect the helium pressure during scanning.\n\n### Solution:\n\nCheck the helium pressure sensor for a leak.\n\n### Response:\n\nThe helium pressure sensor is broken and will not detect the helium pressure during scanning.\n\n### Solution:\n\nCheck the helium pressure sensor for a leak.\n\n### Response:\n\nThe helium pressure sensor is broken and will not detect the helium pressure during scanning.\n\n### Solution:\n\nCheck the helium pressure sensor for a leak.\n\n### Response:\n\nThe helium pressure sensor is broken and will not detect the helium pressure during scanning.\n\n### Solution
4,"The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?","In order to troubleshoot a probe detection issue, you will need to run a software diagnostic on the device. To do so, go into the ""Software"" tab of your ""Device Management"" section in the Device Console and select ""Troubleshoot"". Here, you can then select the ""Probe Detection"" option and click ""Continue"". This will bring up a screen where you can select your probe and confirm its detection.","The ultrasound probe was not detected because the system does not know that it is attached to the ultrasound machine. You can use the following steps to troubleshoot this issue:\n\n- **Step 1:** Connect the probe using a USB cable and reconnect it to the system. This will allow you to view the probe's status in the system.\n- **Step 2:** Check to see if the probe is attached to the ultrasound machine by pressing the ""F"" key on the keyboard. If the probe is attached correctly, then the system should display the probe's status information.\n- **Step 3:** If the probe is attached correctly, then the system should display the probe's status information.\n- **Step 4:** If the probe is attached correctly, then the system should display the probe's status information.\n\n### Answer:\n\nThe ultrasound probe was not detected because the system does not know that it is attached to the ultrasound machine. You can use the following steps to troubleshoot this issue:\n\n- **Step 1:**","To troubleshoot this issue, you can connect the ultrasound probe to another device and check whether the system detects it or not. You may also try disconnecting the ultrasound probe from the system and then reconnecting it again to see if the system detects it or not. If the system still does not detect the ultrasound probe, you can try disabling the ultrasound probe from the system and then re-enabling it from the system. However, in some cases, the ultrasound probe may not be detected because of a problem with the connection between the ultrasound probe and the system. To troubleshoot this issue, you can try connecting the ultrasound probe to another device and check whether the system detects it or not. You may also try disconnecting the ultrasound probe from the system and then reconnecting it again to see if the system detects it or not. If the system still does not detect the ultrasound probe, you can try disabling the ultrasound probe from the system and then re-enabling it from the system. However, in some cases, the ul"
5,The CT gantry will not rotate after startup. Which components should I inspect?,"The CT gantry will not rotate after startup, which components should I inspect?\n\n- The motor shaft bearing.\n- The drive shaft bearing.\n- The drive motor.\n- The drive motor bearing.\n- The control system.\n- The drive shaft.\n- The drive shaft bearing.\n- The drive motor bracket.\n- The drive motor bearing.\n- The drive motor bearing support.\n- The motor shaft bearing support.\n- The motor shaft bearing.\n- The motor shaft bearing support.\n- The motor shaft bearing.\n- The motor shaft bearing.\n- The motor shaft bearing support.\n- The motor shaft bearing support.\n- The motor shaft bearing support.\n- The motor shaft bearing support.\n- The motor shaft bearing support.\n- The motor shaft bearing support.\n- The motor shaft bearing support.\n- The motor shaft bearing support.\n- The motor shaft bearing support.\n- The motor shaft bearing support.\n- The motor shaft bearing support.\n- The motor shaft bearing support.\n- The motor shaft bearing support.",The CT gantry rotates after startup. The CT gantry does not rotate after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates,- The CT gantry does rotate after startup and the CT gantry will rotate after startup. Which components should I inspect?\n- The CT gantry does rotate after startup and the CT gantry will rotate after startup. Which components should I inspect?\n- The CT gantry does rotate after startup and the CT gantry will rotate after startup. Which components should I inspect?\n- The CT gantry does rotate after startup and the CT gantry will rotate after startup. Which components should I inspect?\n- The CT gantry does rotate after startup and the CT gantry will rotate after startup. Which components should I inspect?\n- The CT gantry does rotate after startup and the CT gantry will rotate after startup. Which components should I inspect?\n- The CT gantry does rotate after startup and the CT gantry will rotate after startup. Which components should I inspect?\n- The CT gantry does rotate after startup and the CT gantry will rotate after startup. Which components should I inspect?\n- The CT gantry does rotate after startup and the CT gantry will rotate after startup. Which components should I inspect?\n- The CT gantry does rotate after startup and the CT gantry will
6,MRI images contain zipper artifacts. What usually causes this type of artifact?,"MRI images contain zipper artifacts. The artifact is a result of the fact that MRI scanners generate images by using a continuous x-ray beam, which is directed to the patient's body through an open endoscope. This endoscope is also called the gantry. Because the gantry moves during the scan, it can pass through the patient's body at any given time. This means that each image obtained by the MRI scanner contains information about all points along its path. When the zipper artifact occurs, the zipper passes through the patient's body multiple times during the scan. This means that many zipper artifacts appear in each single image. This artifact can cause subtle differences between the images and may even be visible in the images themselves.\n\n### Question:\n\nWhat happens if the zipper artifact is removed from the image?\n\n### Response:\n\nThe zipper artifact may be removed from the images by performing a series of standard post-scan corrections. These corrections are performed on all images obtained by the MRI scanner. Each post-scan correction will have a different effect on the image.","This artifact is not due to an MRI scan; it is a result of the magnetic field strength in the MRI scanner. The magnetic field strength in the MRI scanner is much higher than the strength of the earth's magnetic field, so the zipper artifact appears when the magnet is turned on.\n\n### Question:\n\nWhich type of artifact is caused by an MRI scan and which type is caused by the magnetic field strength in the MRI scanner?\n\n### Response:\n\nThe zipper artifact is caused by the magnetic field strength in the MRI scanner. The magnetic field strength in the MRI scanner is much higher than the strength of the earth's magnetic field, so the zipper artifact appears when the magnet is turned on.\n\n### Question:\n\nWhich type of artifact is caused by an MRI scan and which type is caused by the magnetic field strength in the MRI scanner?\n\n### Response:\n\nThe zipper artifact is caused by the magnetic field strength in the MRI scanner. The magnetic field strength in the MRI scanner is much higher than the strength of the",* **Zooms:**\n * **MRI images:**\n * **MRI images contain zipper artifacts. What usually causes this type of artifact?**\n* **Zooms:**\n * **MRI images:**\n * **MRI images contain zipper artifacts. What usually causes this type of artifact?**\n\n### Response:\n\n* **Zooms:**\n * **MRI images:**\n * **MRI images contain zipper artifacts. What usually causes this type of artifact?**\n* **Zooms:**\n * **MRI images:**\n * **MRI images contain zipper artifacts. What usually causes this type of artifact?**\n\n### Response:\n\n* **Zooms:**\n * **MRI images:**\n * **MRI images contain zipper artifacts. What usually causes this type of artifact?**\n* **Zooms:**\n * **MRI images:**\n * **MRI images contain zipper artifacts. What usually causes this type

✓ Comparison exported to: /content/outputs/model_response_comparison.csv

============================================================
COMPARISON COMPLETE!
============================================================