# Section 1: Install Required Libraries

In [6]:
pip install --upgrade --force-reinstall Pillow

Collecting Pillow
  Downloading pillow-12.3.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Downloading pillow-12.3.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 27.8 MB/s  0:00:00
Installing collected packages: Pillow
  Attempting uninstall: Pillow
    Found existing installation: pillow 12.2.0
    Uninstalling pillow-12.2.0:
      Successfully uninstalled pillow-12.2.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
unsloth-zoo 2026.7.2 requires datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1, but you have datasets 5.0.0 which is incompatible.
unsloth-zoo 2026.7.2 requires trl!=0.19.0,<=0.24.0,>=0.18.2; sys_platform != "darwin" or platform_machine != "arm64", but you have trl 1.8.0 which is incompatible.
Successfully installed Pillow-12.3.0

In [2]:
# COMPLETE FRESH START - Remove everything and reinstall cleanly
import subprocess
import sys

# Uninstall ALL ML packages to ensure a clean slate
packages_to_remove = ['unsloth', 'transformers', 'datasets', 'trl', 'peft', 'bitsandbytes', 'xformers', 'Pillow']
for pkg in packages_to_remove:
    subprocess.run([sys.executable, '-m', 'pip', 'uninstall', '-y', pkg],
                   capture_output=True, timeout=60)

print("✓ Removed old packages")

# Fresh pip cache
subprocess.run(['pip', 'cache', 'purge'], capture_output=True, timeout=30)
print("✓ Cleared pip cache")

# Install minimal dependencies first
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', 'pip'],
               capture_output=True, timeout=60)

# Install PyTorch (matching the reported CUDA version if possible)
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--no-cache-dir',
                'torch', 'torchvision', 'torchaudio',
                '--index-url', 'https://download.pytorch.org/whl/cu121'], # Changed to cu121 as that's what unsloth typically uses with recent PyTorch
               capture_output=True, timeout=120)
print("✓ PyTorch installed")

# Install unsloth, which will bring its own compatible versions of transformers, peft, trl, etc.
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--no-cache-dir',
                'unsloth[cu121]'], # Explicitly install unsloth for cu121
               capture_output=True, timeout=120)
print("✓ Unsloth installed (including its dependencies like transformers, peft, trl)")

# Finally other general libraries that might not be directly managed by unsloth
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--no-cache-dir',
                'pymupdf', 'pandas', 'numpy', 'scikit-learn',
                'pdfplumber', 'packaging'],
               capture_output=True, timeout=120)
print("✓ Other libraries installed")

# Verify imports
print("\n=== VERIFICATION ===")
try:
    import torch
    print(f"✓ PyTorch {torch.__version__}")
    import transformers
    print(f"✓ Transformers {transformers.__version__}")
    from unsloth import FastLanguageModel
    print(f"✓ Unsloth imported successfully")
    print(f"✓ GPU Available: {torch.cuda.is_available()}")
except Exception as e:
    print(f"✗ Import failed: {e}")

✓ Removed old packages
✓ Cleared pip cache
✓ PyTorch installed
✓ Unsloth installed (including its dependencies like transformers, peft, trl)
✓ Other libraries installed

=== VERIFICATION ===
✓ PyTorch 2.11.0+cu128
✗ Import failed: No module named 'transformers'

In [3]:
# Install Unsloth and its core Colab dependencies
!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"

# Install complementary training and utility libraries
!pip install --no-deps xformers "trl<0.9.0" peft accelerate bitsandbytes

Collecting unsloth @ git+https://github.com/unslothai/unsloth.git (from unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Cloning https://github.com/unslothai/unsloth.git to /tmp/pip-install-cez45_ru/unsloth_d683a5dcb8ce4c9f9347eac74587c88e
  Running command git clone --filter=blob:none --quiet https://github.com/unslothai/unsloth.git /tmp/pip-install-cez45_ru/unsloth_d683a5dcb8ce4c9f9347eac74587c88e
  Resolved https://github.com/unslothai/unsloth.git to commit d105bd7b42ea8d4ecdb3e3364abb605b558c017e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.25.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (13.9.4)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.13.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (6.0.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.6.0)
Collecting unsloth_zoo>=2026.7.2 (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Downloading unsloth_zoo-2026.7.2-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (26.2)
Collecting tyro (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Downloading tyro-1.0.15-py3-none-any.whl.metadata (12 kB)
Collecting transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3 (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Downloading transformers-5.5.0-py3-none-any.whl.metadata (32 kB)
Collecting datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Downloading datasets-4.3.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.2.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (5.9.5)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.47.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.0.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (5.29.6)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.20.1)
Collecting hf_transfer (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (5.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.29.4)
Collecting pyarrow>=21.0.0 (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.7.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2025.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.16.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (4.15.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.8.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.24.2)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.11.0+cu128)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (12.8.90)

In [4]:
pip install -U trl

Requirement already satisfied: trl in /usr/local/lib/python3.12/dist-packages (0.8.6)
Collecting trl
  Downloading trl-1.8.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: accelerate>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from trl) (1.14.0)
Collecting datasets>=4.7.0 (from trl)
  Downloading datasets-5.0.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: packaging>20.0 in /usr/local/lib/python3.12/dist-packages (from trl) (26.2)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl) (5.5.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.11.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (1.20.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (0.8.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.29.4)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (25.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.7.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2025.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.7.0->trl) (0.16.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.5.1)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.15.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.24.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.1.2)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.1)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.0.0->accelerate>=1.4.0->trl) (1.5.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.4.0->trl) (1.3.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.22.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.7.0->trl) (1.17.0)
Downloading trl-1.8.0-py3-none-any.whl (863 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 863.2/863.2 kB 6.1 MB/s  0:00:00
Downloading datasets-5.0.0-py3-none-any.whl (555 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 555.1/555.1 kB 7.8 MB/s  0:00:00
Installing collected packages: datasets, trl
  Attempting uninstall: datasets
    Found existing installation: datasets 4.3.0
    Uninstalling datasets-4.3.0:
      Successfully uninstalled datasets-4.3.0
  Attempting uninstall: trl
    Found existing installation: trl 0.8.6
    Uninstalling trl-0.8.6:
      Successfully uninstalled trl-0.8.6
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [trl]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
unsloth-zoo 2026.7.2 requires datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1, but you have datasets 5.0.0 which is incompatible.
unsloth-zoo 2026.7.2 requires trl!=0.19.0,<=0.24.0,>=0.18.2; sys_platform != "darwin" or platform_machine != "arm64", but you have trl 1.8.0 which is incompatible.
Successfully installed datasets-5.0.0 trl-1.8.0

In [1]:
# Import required libraries
import os
import re
import gc
import json
import time
import warnings
import unicodedata
from typing import List, Dict, Any, Tuple
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import fitz  # PyMuPDF

from datasets import Dataset, load_dataset
from transformers import TextIteratorStreamer # This should now be available
from threading import Thread

# Unsloth imports (moved here for consolidation after installation)
import unsloth
from unsloth import FastLanguageModel, is_bfloat16_supported
from unsloth.chat_templates import get_chat_template

# Training imports (if needed, otherwise remove)
from trl import SFTTrainer, SFTConfig # This should now be available

warnings.filterwarnings("ignore")

# Verify GPU availability
assert torch.cuda.is_available(), "GPU not found. Please ensure CUDA is available."
print(f"✓ GPU Available: {torch.cuda.get_device_name(0)}")
print(f"✓ CUDA Version: {torch.version.cuda}")
print(f"✓ PyTorch Version: {torch.__version__}")

/usr/local/lib/python3.12/dist-packages/unsloth/__init__.py:1427: UserWarning: WARNING: Unsloth should be imported before [transformers] to ensure all optimizations are applied. Your code may run slower or encounter memory issues without these optimizations.

Please restructure your imports with 'import unsloth' at the top of your file.
  from ._gpu_init import *

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

Accessing `is_flash_linear_attention_available` from `.models.aria.image_processing_aria`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.aria.image_processing_pil_aria`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.auto.image_processing_auto`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.beit.image_processing_beit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.beit.image_processing_pil_beit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.bit.image_processing_bit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.bit.image_processing_pil_bit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.blip.image_processing_blip`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.blip.image_processing_pil_blip`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.bridgetower.image_processing_bridgetower`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.bridgetower.image_processing_pil_bridgetower`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.chameleon.image_processing_chameleon`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.chameleon.image_processing_pil_chameleon`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.chinese_clip.image_processing_chinese_clip`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.chinese_clip.image_processing_chinese_pil_clip`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.chmv2.image_processing_chmv2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.clip.image_processing_clip`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.clip.image_processing_pil_clip`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.cohere2_vision.image_processing_cohere2_vision`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.conditional_detr.image_processing_conditional_detr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.conditional_detr.image_processing_pil_conditional_detr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.convnext.image_processing_convnext`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.convnext.image_processing_pil_convnext`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deepseek_vl.image_processing_deepseek_vl`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deepseek_vl.image_processing_pil_deepseek_vl`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deepseek_vl_hybrid.image_processing_deepseek_vl_hybrid`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deepseek_vl_hybrid.image_processing_pil_deepseek_vl_hybrid`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deformable_detr.image_processing_deformable_detr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deformable_detr.image_processing_pil_deformable_detr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deit.image_processing_deit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deit.image_processing_pil_deit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.depth_pro.image_processing_depth_pro`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.detr.image_processing_detr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.detr.image_processing_pil_detr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.dinov3_vit.image_processing_dinov3_vit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.donut.image_processing_donut`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.donut.image_processing_pil_donut`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.dpt.image_processing_dpt`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.dpt.image_processing_pil_dpt`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.efficientloftr.image_processing_efficientloftr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.efficientloftr.image_processing_pil_efficientloftr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.efficientnet.image_processing_efficientnet`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.efficientnet.image_processing_pil_efficientnet`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.emu3.image_processing_emu3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.eomt.image_processing_eomt`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.eomt.image_processing_pil_eomt`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.ernie4_5_vl_moe.image_processing_ernie4_5_vl_moe`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.ernie4_5_vl_moe.image_processing_pil_ernie4_5_vl_moe`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.flava.image_processing_flava`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.flava.image_processing_pil_flava`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.fuyu.image_processing_fuyu`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.fuyu.image_processing_pil_fuyu`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.gemma3.image_processing_gemma3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.gemma3.image_processing_pil_gemma3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.gemma4.image_processing_gemma4`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.gemma4.image_processing_pil_gemma4`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glm46v.image_processing_glm46v`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glm46v.image_processing_pil_glm46v`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glm4v.image_processing_glm4v`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glm4v.image_processing_pil_glm4v`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glm_image.image_processing_glm_image`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glm_image.image_processing_pil_glm_image`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glpn.image_processing_glpn`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glpn.image_processing_pil_glpn`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.got_ocr2.image_processing_got_ocr2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.got_ocr2.image_processing_pil_got_ocr2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.grounding_dino.image_processing_grounding_dino`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.grounding_dino.image_processing_pil_grounding_dino`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.idefics.image_processing_idefics`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.idefics.image_processing_pil_idefics`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.idefics2.image_processing_idefics2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.idefics2.image_processing_pil_idefics2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.idefics3.image_processing_idefics3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.idefics3.image_processing_pil_idefics3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.imagegpt.image_processing_imagegpt`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.imagegpt.image_processing_pil_imagegpt`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.janus.image_processing_janus`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.janus.image_processing_pil_janus`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.kosmos2_5.image_processing_kosmos2_5`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.kosmos2_5.image_processing_pil_kosmos2_5`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.layoutlmv2.image_processing_layoutlmv2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.layoutlmv2.image_processing_pil_layoutlmv2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.layoutlmv3.image_processing_layoutlmv3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.layoutlmv3.image_processing_pil_layoutlmv3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.levit.image_processing_levit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.

🦥 Unsloth Zoo will now patch everything to make training faster!
✓ GPU Available: Tesla T4
✓ CUDA Version: 12.8
✓ PyTorch Version: 2.11.0+cu128

# Section 2: Configuration & File Paths

In [2]:
# ==========================================
# Configuration Parameters
# ==========================================

# Model Configuration
BASE_MODEL = "unsloth/tinyllama-bnb-4bit"  # Open source model
# Alternative options:
# "unsloth/llama-2-7b-bnb-4bit"
# "unsloth/tinyllama-bnb-4bit"
# "unsloth/mistral-7b-bnb-4bit"

MAX_SEQ_LENGTH = 2048
SEED = 42

# Data Paths (Google Colab - files from /content folder)
PDF_FILE_PATH = "/content/data.pdf"  # Your PDF file
JSONL_INSTRUCTION_FILE = "/content/instructions.jsonl"  # Your instruction JSONL

# Validate that input files exist
for file_path in [PDF_FILE_PATH, JSONL_INSTRUCTION_FILE]:
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"File not found: {file_path}. Please upload this file to /content folder in Colab.")

# LoRA Configuration
LORA_R = 16  # LoRA rank
LORA_ALPHA = 32  # LoRA alpha
LORA_DROPOUT = 0.05
LORA_TARGET_MODULES = ["q_proj", "k_proj", "v_proj", "o_proj"]

# QLoRA Configuration (for 4-bit quantization - already done via model loading)
USE_QLORA = True  # Already using 4-bit via model name

# Training Configuration
BATCH_SIZE = 2
GRADIENT_ACCUMULATION_STEPS = 4
NUM_TRAIN_EPOCHS = 3
WARMUP_STEPS = 50
LOGGING_STEPS = 10
SAVE_STEPS = 500

# Learning rates for different stages
STAGE1_LR = 2e-4  # Non-instruction fine-tuning
STAGE2_LR = 1e-4  # Instruction fine-tuning

# PDF Processing
MIN_CHARS_PER_CHUNK = 100
CHUNK_OVERLAP = 50

# Output directories (Google Colab)
OUTPUT_DIR = "/content/outputs"
STAGE1_ADAPTER_DIR = f"{OUTPUT_DIR}/stage1_non_instruction_adapter"
STAGE1_MERGED_DIR = f"{OUTPUT_DIR}/stage1_non_instruction_merged"
STAGE2_ADAPTER_DIR = f"{OUTPUT_DIR}/stage2_instruction_adapter"
STAGE2_MERGED_DIR = f"{OUTPUT_DIR}/stage2_instruction_merged"
FINAL_MERGED_DIR = f"{OUTPUT_DIR}/final_merged_model"

# Create output directories
for dir_path in [OUTPUT_DIR, STAGE1_ADAPTER_DIR, STAGE1_MERGED_DIR,
                  STAGE2_ADAPTER_DIR, STAGE2_MERGED_DIR, FINAL_MERGED_DIR]:
    os.makedirs(dir_path, exist_ok=True)

print("✓ Configuration loaded")
print(f"✓ Input files validated from /content folder")
print(f"✓ Output directories created at: {OUTPUT_DIR}")

✓ Configuration loaded
✓ Input files validated from /content folder
✓ Output directories created at: /content/outputs

# Section 3: Utility Functions for PDF Processing & Data Handling

In [3]:
def extract_pdf_text(pdf_path: str) -> List[Dict[str, Any]]:
    """
    Extract text from PDF file with page information

    Args:
        pdf_path: Path to PDF file

    Returns:
        List of dictionaries containing page number and text
    """
    pages = []

    try:
        with fitz.open(pdf_path) as doc:
            for page_num, page in enumerate(doc, start=1):
                text = page.get_text("text").strip()
                if text:
                    pages.append({
                        "page": page_num,
                        "text": text,
                    })
    except Exception as e:
        print(f"Error extracting PDF: {e}")
        return []

    print(f"✓ Extracted {len(pages)} pages from PDF")
    return pages


def clean_text(text: str) -> str:
    """
    Clean and normalize text for training

    Args:
        text: Raw text to clean

    Returns:
        Cleaned text
    """
    # Unicode normalization
    text = unicodedata.normalize("NFKC", text)
    text = text.replace("\u200b", "").replace("\ufeff", "")

    # Fix hyphenated words broken across lines
    text = re.sub(r"(\w)-\n(\w)", r"\1\2", text)

    # Remove page numbers
    text = re.sub(r"(?m)^\s*\d+\s*$", "", text)

    # Normalize spaces
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()


def chunk_text(text: str, chunk_size: int = 512, overlap: int = 50) -> List[str]:
    """
    Split text into overlapping chunks

    Args:
        text: Text to chunk
        chunk_size: Maximum characters per chunk
        overlap: Number of overlapping characters between chunks

    Returns:
        List of text chunks
    """
    chunks = []
    start = 0

    while start < len(text):
        end = min(start + chunk_size, len(text))

        # Try to break at sentence boundary
        if end < len(text):
            last_period = text.rfind(".", start, end)
            if last_period > start:
                end = last_period + 1

        chunk = text[start:end].strip()
        if len(chunk) >= MIN_CHARS_PER_CHUNK:
            chunks.append(chunk)

        start = end - overlap if end < len(text) else end

    return chunks


def clear_gpu_memory():
    """Clear GPU memory cache"""
    gc.collect()
    torch.cuda.empty_cache()


def print_trainable_params(model):
    """Print model trainable vs total parameters"""
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total_params = sum(p.numel() for p in model.parameters())

    print(f"Trainable params: {trainable_params:,} / {total_params:,}")
    print(f"Trainable %: {100 * trainable_params / total_params:.2f}%")

print("✓ Utility functions defined")

✓ Utility functions defined

In [4]:
def create_dataset_from_pdf(pdf_path: str) -> Dataset:
    """
    Create training dataset from PDF file

    Args:
        pdf_path: Path to PDF file

    Returns:
        HuggingFace Dataset
    """
    pages = extract_pdf_text(pdf_path)
    records = []

    for page in pages:
        cleaned_text = clean_text(page["text"])
        chunks = chunk_text(cleaned_text, chunk_size=512, overlap=CHUNK_OVERLAP)

        for chunk_id, chunk in enumerate(chunks):
            if len(chunk) >= MIN_CHARS_PER_CHUNK:
                records.append({
                    "text": chunk,
                    "source_page": page["page"],
                    "chunk_id": chunk_id,
                })

    print(f"✓ Created {len(records)} text chunks from PDF")
    if records:
        print(f"Sample chunk:\n{records[0]['text'][:300]}...")

    return Dataset.from_list(records)


def load_instruction_dataset_from_jsonl(jsonl_path: str) -> Dataset:
    """
    Load instruction dataset from JSONL file

    Args:
        jsonl_path: Path to JSONL file with format:
                   {"instruction": "...", "input": "...", "output": "..."}

    Returns:
        HuggingFace Dataset
    """
    records = []

    try:
        with open(jsonl_path, 'r') as f:
            for line in f:
                if line.strip():
                    record = json.loads(line)
                    # Ensure required fields exist
                    record.setdefault('instruction', '')
                    record.setdefault('input', '')
                    record.setdefault('output', '')
                    records.append(record)
    except Exception as e:
        print(f"Error loading JSONL: {e}")
        return Dataset.from_list([])

    print(f"✓ Loaded {len(records)} instruction examples from JSONL")
    if records:
        print(f"Sample instruction:\n{records[0]}")

    return Dataset.from_list(records)


def format_instruction_prompt(instruction: str, input_text: str = "", output_text: str = "") -> str:
    """
    Format instruction in alpaca-style template

    Args:
        instruction: Main instruction
        input_text: Optional input context
        output_text: Expected output (for training)

    Returns:
        Formatted prompt string
    """
    instruction = str(instruction).strip()
    input_text = str(input_text).strip()
    output_text = str(output_text).strip()

    if input_text:
        prompt = f"### Instruction:\n{instruction}\n\n### Input:\n{input_text}\n\n### Response:\n{output_text}"
    else:
        prompt = f"### Instruction:\n{instruction}\n\n### Response:\n{output_text}"

    return prompt


def format_instruction_dataset(dataset: Dataset) -> Dataset:
    """
    Format instruction dataset with proper prompts

    Args:
        dataset: Raw instruction dataset

    Returns:
        Formatted dataset with 'text' field
    """
    def format_row(row):
        prompt = format_instruction_prompt(
            instruction=row.get('instruction', ''),
            input_text=row.get('input', ''),
            output_text=row.get('output', '')
        )
        return {"text": prompt}

    formatted = dataset.map(format_row, remove_columns=dataset.column_names)
    print(f"✓ Formatted {len(formatted)} instruction examples")
    if len(formatted) > 0:
        print(f"Sample formatted text:\n{formatted[0]['text'][:300]}...")

    return formatted

print("✓ PDF and instruction processing functions defined")

✓ PDF and instruction processing functions defined

# Section 4: Load Tokenizer and Model with LoRA/QLoRA

In [5]:
def load_model_with_lora(model_name_or_path: str, load_in_4bit: bool = True):
    """
    Load model with LoRA/QLoRA configuration using Unsloth

    Args:
        model_name_or_path: Model name or path
        load_in_4bit: Whether to use 4-bit quantization (QLoRA)

    Returns:
        Tuple of (model, tokenizer)
    """
    print(f"\nLoading model: {model_name_or_path}")
    print(f"4-bit Quantization (QLoRA): {load_in_4bit}")

    # Load model and tokenizer using Unsloth
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=model_name_or_path,
        max_seq_length=MAX_SEQ_LENGTH,
        dtype=None,
        load_in_4bit=load_in_4bit,
    )

    # Setup tokenizer
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    # Apply LoRA configuration
    print("\nApplying LoRA configuration:")
    print(f"  LoRA Rank (r): {LORA_R}")
    print(f"  LoRA Alpha: {LORA_ALPHA}")
    print(f"  LoRA Dropout: {LORA_DROPOUT}")

    model = FastLanguageModel.get_peft_model(
        model,
        r=LORA_R,
        lora_alpha=LORA_ALPHA,
        target_modules=LORA_TARGET_MODULES,
        lora_dropout=LORA_DROPOUT,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=SEED,
    )

    print("\nModel loaded successfully!")
    print_trainable_params(model)

    return model, tokenizer


# Load base model
print("=" * 60)
print("LOADING BASE MODEL")
print("=" * 60)

base_model, base_tokenizer = load_model_with_lora(BASE_MODEL, load_in_4bit=True)
clear_gpu_memory()

print("\n✓ Base model ready for training")

============================================================
LOADING BASE MODEL
============================================================

Loading model: unsloth/tinyllama-bnb-4bit
4-bit Quantization (QLoRA): True
==((====))==  Unsloth 2026.7.2: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Unsloth: Will load unsloth/tinyllama-bnb-4bit as a legacy tokenizer.
Unsloth: Dropout = 0 is supported for fast patching. You are using dropout = 0.05.
Unsloth will patch all other layers, except LoRA matrices, causing a performance hit.

Applying LoRA configuration:
  LoRA Rank (r): 16
  LoRA Alpha: 32
  LoRA Dropout: 0.05

Unsloth 2026.7.2 patched 22 layers with 0 QKV layers, 0 O layers and 0 MLP layers.

Model loaded successfully!
Trainable params: 4,505,600 / 620,111,872
Trainable %: 0.73%

✓ Base model ready for training

# Section 5: Extract and Process PDF Text

In [6]:
# Check if PDF exists, if not create a sample dataset
if os.path.exists(PDF_FILE_PATH):
    print(f"Loading PDF from: {PDF_FILE_PATH}")
    pdf_dataset = create_dataset_from_pdf(PDF_FILE_PATH)
else:
    print(f"⚠ PDF file not found at {PDF_FILE_PATH}")
    print("Creating sample dataset for demonstration...")

    # Create sample data for demonstration
    sample_texts = [

        "The X-ray tube generates radiation that passes through the patient while detectors convert transmitted photons into electrical signals."
         "Common failures include tube arcing, tube overheating, detector calibration drift,"
        "DAS communication faults, gantry rotation errors, chiller malfunction, encoder faults, slip-ring wear and table motion problems",

        "A CT scanner consists of the gantry, X-ray tube, high-voltage generator, detector array, data acquisition system, slip ring, cooling system, patient table, reconstruction computers and operator console. "
        "The X-ray tube generates radiation that passes through the patient while detectors convert transmitted photons into electrical signals. "
        "Common failures include tube arcing, tube overheating, detector calibration drift, DAS communication faults, gantry rotation errors, chiller malfunction, encoder faults, slip-ring wear and table motion problems. "
        "Ring artifacts usually indicate detector calibration issues or failed detector channels." ,


        "A CT scanner consists of the gantry, X-ray tube, high-voltage generator, detector array, data acquisition system, slip ring, "
        "cooling system, patient table, reconstruction computers and operator console."
        "The X-ray tube generates radiation that passes through the patient while detectors convert transmitted photons into electrical signals",
    ]

    records = [{"text": text, "source_page": i, "chunk_id": 0}
               for i, text in enumerate(sample_texts, 1)]
    pdf_dataset = Dataset.from_list(records)
    print(f"✓ Created sample dataset with {len(pdf_dataset)} examples")

print(f"\n✓ Dataset size: {len(pdf_dataset)} samples")
print(f"Sample text:\n{pdf_dataset[0]['text'][:250]}...")

Loading PDF from: /content/data.pdf
✓ Extracted 137 pages from PDF
✓ Created 1411 text chunks from PDF
Sample chunk:
Medical Imaging Equipment Failure Diagnosis Knowledge Base
Introduction
This handbook provides domain-specific knowledge for troubleshooting CT scanners, MRI
systems, ultrasound systems, digital radiography, mammography, fluoroscopy, C-arms and
PET/CT systems. It explains major subsystems, opera...

✓ Dataset size: 1411 samples
Sample text:
Medical Imaging Equipment Failure Diagnosis Knowledge Base
Introduction
This handbook provides domain-specific knowledge for troubleshooting CT scanners, MRI
systems, ultrasound systems, digital radiography, mammography, fluoroscopy, C-arms and
P...

# Section 6: Stage 1 - Non-Instruction Fine-Tuning on Raw PDF Text

In [7]:
print("\n" + "=" * 60)
print("STAGE 1: NON-INSTRUCTION FINE-TUNING")
print("Training on raw PDF text")
print("=" * 60)

# Reload model for training
clear_gpu_memory()
stage1_model, tokenizer = load_model_with_lora(BASE_MODEL, load_in_4bit=True)

# Configure training
stage1_config = SFTConfig(
    output_dir=f"{OUTPUT_DIR}/stage1_logs",
    num_train_epochs=NUM_TRAIN_EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
    learning_rate=STAGE1_LR,
    warmup_steps=WARMUP_STEPS,
    logging_steps=LOGGING_STEPS,
    save_strategy="steps",
    save_steps=SAVE_STEPS,
    report_to="none",
    fp16=not is_bfloat16_supported(),
    bf16=is_bfloat16_supported(),
    optim="adamw_8bit",
    dataset_text_field="text",
    max_seq_length=MAX_SEQ_LENGTH,
    packing=True,
    seed=SEED,
)

print("\nTraining Configuration:")
print(f"  Epochs: {NUM_TRAIN_EPOCHS}")
print(f"  Batch Size: {BATCH_SIZE}")
print(f"  Learning Rate: {STAGE1_LR}")
print(f"  Max Seq Length: {MAX_SEQ_LENGTH}")

# Create trainer
stage1_trainer = SFTTrainer(
    model=stage1_model,
    tokenizer=tokenizer,
    train_dataset=pdf_dataset,
    args=stage1_config,
)

# Train
print("\nStarting Stage 1 training...")
start_time = time.time()
stage1_train_result = stage1_trainer.train()
training_time = time.time() - start_time

print(f"\n✓ Stage 1 Training Complete!")
print(f"Training time: {training_time:.2f}s")
print(f"Final loss: {stage1_train_result.training_loss:.4f}")

# Save adapter
print(f"\nSaving Stage 1 adapter to: {STAGE1_ADAPTER_DIR}")
stage1_model.save_pretrained(STAGE1_ADAPTER_DIR)
tokenizer.save_pretrained(STAGE1_ADAPTER_DIR)

# Save merged model
print(f"Saving Stage 1 merged model to: {STAGE1_MERGED_DIR}")
stage1_model.save_pretrained_merged(
    STAGE1_MERGED_DIR,
    tokenizer,
    save_method="merged_16bit",
)

print("\n✓ Stage 1 artifacts saved")
clear_gpu_memory()

============================================================
STAGE 1: NON-INSTRUCTION FINE-TUNING
Training on raw PDF text
============================================================

Loading model: unsloth/tinyllama-bnb-4bit
4-bit Quantization (QLoRA): True
==((====))==  Unsloth 2026.7.2: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Unsloth: Will load unsloth/tinyllama-bnb-4bit as a legacy tokenizer.

Applying LoRA configuration:
  LoRA Rank (r): 16
  LoRA Alpha: 32
  LoRA Dropout: 0.05

Model loaded successfully!
Trainable params: 4,505,600 / 620,111,872
Trainable %: 0.73%

Training Configuration:
  Epochs: 3
  Batch Size: 2
  Learning Rate: 0.0002
  Max Seq Length: 2048

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/1411 [00:00<?, ? examples/s]

Unsloth: Packing train dataset (num_proc=6):   0%|          | 0/1411 [00:00<?, ? examples/s]

🦥 Unsloth: Packing enabled - training is >2x faster and uses less VRAM!

Starting Stage 1 training...

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 79 | Num Epochs = 3 | Total steps = 30
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 4,505,600 of 1,104,553,984 (0.41% trained)
`use_return_dict` is deprecated! Use `return_dict` instead!

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

Unsloth: Restored added_tokens_decoder metadata in /content/outputs/stage1_logs/checkpoint-30/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in /content/outputs/stage1_logs/checkpoint-30.

✓ Stage 1 Training Complete!
Training time: 215.91s
Final loss: 3.2288

Saving Stage 1 adapter to: /content/outputs/stage1_non_instruction_adapter

Unsloth: Restored added_tokens_decoder metadata in /content/outputs/stage1_non_instruction_adapter/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in /content/outputs/stage1_non_instruction_adapter.

Saving Stage 1 merged model to: /content/outputs/stage1_non_instruction_merged

config.json:   0%|          | 0.00/749 [00:00<?, ?B/s]

Unsloth: Restored added_tokens_decoder metadata in /content/outputs/stage1_non_instruction_merged/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in /content/outputs/stage1_non_instruction_merged.

Found HuggingFace hub cache directory: /root/.cache/huggingface/hub
Checking cache directory for required files...
Cache check failed: model.safetensors not found in local cache.
Not all required files found in cache. Will proceed with downloading.
Checking cache directory for required files...
Cache check failed: tokenizer.model not found in local cache.
Not all required files found in cache. Will proceed with downloading.

Unsloth: Preparing safetensor model files:   0%|          | 0/1 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/2.20G [00:00<?, ?B/s]

Unsloth: Preparing safetensor model files: 100%|██████████| 1/1 [00:23<00:00, 23.85s/it]
Unsloth: Merging weights into 16bit: 100%|██████████| 1/1 [00:43<00:00, 43.25s/it]

Unsloth: Merge process complete. Saved to `/content/outputs/stage1_non_instruction_merged`

✓ Stage 1 artifacts saved

# Section 7: Load and Process Instruction Dataset from JSONL

In [8]:
# Load instruction dataset
if os.path.exists(JSONL_INSTRUCTION_FILE):
    print(f"Loading instruction dataset from: {JSONL_INSTRUCTION_FILE}")
    instruction_dataset = load_instruction_dataset_from_jsonl(JSONL_INSTRUCTION_FILE)
    if not instruction_dataset and os.path.exists(JSONL_INSTRUCTION_FILE): # Check if loading failed but file exists
        print("⚠ Failed to load instruction JSONL, using sample dataset instead.")
        sample_instructions = [
            {
                "instruction": "What causes CT Scanner failure scenario?",
                "input": "",
                "output": "Common causes include power issues, cooling problems, cable damage, component aging, calibration drift, communication faults, or mechanical wear. Diagnosis should begin with visual inspection and system logs. "
            },
            {
                "instruction": "What preventive maintenance is required for Ultrasound item",
                "input": "",
                "output": "Perform routine cleaning, inspect connectors, verify calibration, check cooling performance, review logs, and replace worn consumables according to maintenance schedules. "
            },
            {
                "instruction": "What is the function of the PET-CT component ?",
                "input": "",
                "output": "The referenced component in the PET-CT performs its designated operational role and should be inspected according to the service manual if abnormal behavior is observed. "
            },
            {
                "instruction": "What is the function of the Mammography component ?",
                "input": "",
                "output": "The referenced component in the Mammography performs its designated operational role and should be inspected according to the service manual if abnormal behavior is observed."
            },
            {
                "instruction": "Why is image quality degraded on MRI case?",
                "input": "",
                "output": "Image degradation may result from calibration errors, detector or probe issues, motion artifacts, electronic noise, or reconstruction problems."
            },
        ]
        instruction_dataset = Dataset.from_list(sample_instructions)
        print(f"✓ Created sample instruction dataset with {len(instruction_dataset)} examples")
else:
    print(f"⚠ Instruction JSONL file not found at {JSONL_INSTRUCTION_FILE}")
    print("Creating sample instruction dataset for demonstration...")

    # Create sample instruction dataset
    sample_instructions = [
        {
            "instruction": "What causes CT Scanner failure scenario?",
            "input": "",
            "output": "Common causes include power issues, cooling problems, cable damage, component aging, calibration drift, communication faults, or mechanical wear. Diagnosis should begin with visual inspection and system logs. "
        },
        {
            "instruction": "What preventive maintenance is required for Ultrasound item",
            "input": "",
            "output": "Perform routine cleaning, inspect connectors, verify calibration, check cooling performance, review logs, and replace worn consumables according to maintenance schedules. "
        },
        {
            "instruction": "What is the function of the PET-CT component ?",
            "input": "",
            "output": "The referenced component in the PET-CT performs its designated operational role and should be inspected according to the service manual if abnormal behavior is observed. "
        },
        {
            "instruction": "What is the function of the Mammography component ?",
            "input": "",
            "output": "The referenced component in the Mammography performs its designated operational role and should be inspected according to the service manual if abnormal behavior is observed."
        },
        {
            "instruction": "Why is image quality degraded on MRI case?",
            "input": "",
            "output": "Image degradation may result from calibration errors, detector or probe issues, motion artifacts, electronic noise, or reconstruction problems."
        },
    ]

    instruction_dataset = Dataset.from_list(sample_instructions)
    print(f"✓ Created sample instruction dataset with {len(instruction_dataset)} examples")

# Format the instruction dataset
formatted_instruction_dataset = format_instruction_dataset(instruction_dataset)

print(f"\n✓ Formatted instruction dataset: {len(formatted_instruction_dataset)} samples")
# Only attempt to print sample if the dataset is not empty
if len(formatted_instruction_dataset) > 0:
    print(f"Sample formatted example:\n{formatted_instruction_dataset[0]['text'][:400]}...")

Loading instruction dataset from: /content/instructions.jsonl
✓ Loaded 300 instruction examples from JSONL
Sample instruction:
{'instruction': 'What is the function of the CT Scanner component 1?', 'input': '', 'output': 'The referenced component in the CT Scanner performs its designated operational role and should be inspected according to the service manual if abnormal behavior is observed.', 'source_page': 1, 'topic': 'CT Scanner - Components'}

Map:   0%|          | 0/300 [00:00<?, ? examples/s]

✓ Formatted 300 instruction examples
Sample formatted text:
### Instruction:
What is the function of the CT Scanner component 1?

### Response:
The referenced component in the CT Scanner performs its designated operational role and should be inspected according to the service manual if abnormal behavior is observed....

✓ Formatted instruction dataset: 300 samples
Sample formatted example:
### Instruction:
What is the function of the CT Scanner component 1?

### Response:
The referenced component in the CT Scanner performs its designated operational role and should be inspected according to the service manual if abnormal behavior is observed....

# Section 8: Stage 2 - Instruction-Based Fine-Tuning

In [9]:
print("\n" + "=" * 60)
print("STAGE 2: INSTRUCTION-BASED FINE-TUNING")
print("Training on formatted instruction data")
print("=" * 60)

# Load the Stage 1 merged model as starting point
clear_gpu_memory()
print(f"\nLoading Stage 1 merged model from: {STAGE1_MERGED_DIR}")
stage2_model, tokenizer = load_model_with_lora(STAGE1_MERGED_DIR, load_in_4bit=True)

# Configure training for instruction fine-tuning
stage2_config = SFTConfig(
    output_dir=f"{OUTPUT_DIR}/stage2_logs",
    num_train_epochs=NUM_TRAIN_EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
    learning_rate=STAGE2_LR,
    warmup_steps=WARMUP_STEPS,
    logging_steps=LOGGING_STEPS,
    save_strategy="steps",
    save_steps=SAVE_STEPS,
    report_to="none",
    fp16=not is_bfloat16_supported(),
    bf16=is_bfloat16_supported(),
    optim="adamw_8bit",
    dataset_text_field="text",
    max_seq_length=MAX_SEQ_LENGTH,
    packing=True,
    seed=SEED,
)

print("\nTraining Configuration:")
print(f"  Epochs: {NUM_TRAIN_EPOCHS}")
print(f"  Batch Size: {BATCH_SIZE}")
print(f"  Learning Rate: {STAGE2_LR}")
print(f"  Max Seq Length: {MAX_SEQ_LENGTH}")

# Create trainer for instruction fine-tuning
stage2_trainer = SFTTrainer(
    model=stage2_model,
    tokenizer=tokenizer,
    train_dataset=formatted_instruction_dataset,
    args=stage2_config,
)

# Train
print("\nStarting Stage 2 training...")
start_time = time.time()
stage2_train_result = stage2_trainer.train()
training_time = time.time() - start_time

print(f"\n✓ Stage 2 Training Complete!")
print(f"Training time: {training_time:.2f}s")
print(f"Final loss: {stage2_train_result.training_loss:.4f}")

# Save adapter
print(f"\nSaving Stage 2 adapter to: {STAGE2_ADAPTER_DIR}")
stage2_model.save_pretrained(STAGE2_ADAPTER_DIR)
tokenizer.save_pretrained(STAGE2_ADAPTER_DIR)

# Save merged model
print(f"Saving Stage 2 merged model to: {STAGE2_MERGED_DIR}")
stage2_model.save_pretrained_merged(
    STAGE2_MERGED_DIR,
    tokenizer,
    save_method="merged_16bit",
)

print("\n✓ Stage 2 artifacts saved")
clear_gpu_memory()

============================================================
STAGE 2: INSTRUCTION-BASED FINE-TUNING
Training on formatted instruction data
============================================================

Loading Stage 1 merged model from: /content/outputs/stage1_non_instruction_merged

Loading model: /content/outputs/stage1_non_instruction_merged
4-bit Quantization (QLoRA): True
==((====))==  Unsloth 2026.7.2: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Unsloth: Will load /content/outputs/stage1_non_instruction_merged as a legacy tokenizer.

Applying LoRA configuration:
  LoRA Rank (r): 16
  LoRA Alpha: 32
  LoRA Dropout: 0.05

Model loaded successfully!
Trainable params: 4,505,600 / 620,111,872
Trainable %: 0.73%

Training Configuration:
  Epochs: 3
  Batch Size: 2
  Learning Rate: 0.0001
  Max Seq Length: 2048
Unsloth: Sample packing skipped (custom data collator detected).

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/300 [00:00<?, ? examples/s]

Starting Stage 2 training...

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 300 | Num Epochs = 3 | Total steps = 114
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 4,505,600 of 1,104,553,984 (0.41% trained)

Unsloth: Restored added_tokens_decoder metadata in /content/outputs/stage2_logs/checkpoint-114/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in /content/outputs/stage2_logs/checkpoint-114.
Unsloth: Restored added_tokens_decoder metadata in /content/outputs/stage2_instruction_adapter/tokenizer_config.json.
Unsloth: Preserved sentencepiece asset `tokenizer.model` in /content/outputs/stage2_instruction_adapter.

✓ Stage 2 Training Complete!
Training time: 171.24s
Final loss: 0.7912

Saving Stage 2 adapter to: /content/outputs/stage2_instruction_adapter
Saving Stage 2 merged model to: /content/outputs/stage2_instruction_merged

Unsloth: Restored added_tokens_decoder metadata in /content/outputs/stage2_instruction_merged/tokenizer_config.json.

Detected local model directory: /content/outputs/stage1_non_instruction_merged
Copied tokenizer.model from local model directory
Found HuggingFace hub cache directory: /root/.cache/huggingface/hub

Unsloth: Preparing safetensor model files: 100%|██████████| 1/1 [00:20<00:00, 20.82s/it]

Copied model.safetensors from local model directory

Unsloth: Merging weights into 16bit: 100%|██████████| 1/1 [00:41<00:00, 41.53s/it]

Unsloth: Merge process complete. Saved to `/content/outputs/stage2_instruction_merged`

✓ Stage 2 artifacts saved

# Section 9: Inference Functions and Interactive Bot

In [10]:
def generate_response(model, tokenizer, instruction: str, input_text: str = "", max_new_tokens: int = 256) -> str:
    """
    Generate response using the model

    Args:
        model: Fine-tuned model
        tokenizer: Model tokenizer
        instruction: User instruction
        input_text: Optional input context
        max_new_tokens: Maximum tokens to generate

    Returns:
        Generated response
    """
    # Prepare prompt
    FastLanguageModel.for_inference(model)

    prompt = format_instruction_prompt(instruction, input_text)
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=MAX_SEQ_LENGTH).to("cuda")

    # Generate
    with torch.inference_mode():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
            repetition_penalty=1.1,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    # Decode response
    response = tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True).strip()
    return response


def interactive_bot(model, tokenizer, stage_name: str):
    """
    Interactive bot for testing model

    Args:
        model: Fine-tuned model
        tokenizer: Model tokenizer
        stage_name: Name of the model stage
    """
    print(f"\n{'='*60}")
    print(f"Interactive Bot - {stage_name}")
    print(f"{'='*60}")
    print("Enter 'quit' to exit\n")

    test_queries = [
        ("What causes CT Scanner failure scenario?", ""),
        ("What is the function of the Mammography component", ""),
        ("Why is image quality degraded on MRI case?", ""),
    ]

    for instruction, input_text in test_queries:
        print(f"\n[User] Instruction: {instruction}")
        if input_text:
            print(f"[User] Input: {input_text}")

        response = generate_response(model, tokenizer, instruction, input_text)
        print(f"[{stage_name}] Response: {response[:500]}...")
        print("-" * 60)


def batch_generate_responses(model, tokenizer, test_queries: List[Tuple[str, str]]) -> List[str]:
    """
    Generate responses for multiple queries

    Args:
        model: Fine-tuned model
        tokenizer: Model tokenizer
        test_queries: List of (instruction, input) tuples

    Returns:
        List of generated responses
    """
    responses = []
    for instruction, input_text in test_queries:
        response = generate_response(model, tokenizer, instruction, input_text)
        responses.append(response)

    return responses

print("✓ Inference functions defined")

✓ Inference functions defined

# Section 10: Load Models for Inference & Comparison

In [11]:
# Load base model for comparison
print("\n" + "=" * 60)
print("LOADING MODELS FOR INFERENCE")
print("=" * 60)

clear_gpu_memory()

print("\n1. Loading base model...")
base_model, base_tokenizer = FastLanguageModel.from_pretrained(
    model_name=BASE_MODEL,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,
    load_in_4bit=True,
    device_map="cuda:0" # Explicitly place model on GPU 0 to avoid problematic CPU offload validation
)
if base_tokenizer.pad_token is None:
    base_tokenizer.pad_token = base_tokenizer.eos_token
base_tokenizer.padding_side = "right"
print("✓ Base model loaded")

# Load Stage 1 (Non-instruction) model
print("\n2. Loading Stage 1 (Non-instruction) fine-tuned model...")
clear_gpu_memory() # Clear memory before loading next model to be safe
stage1_model, stage1_tokenizer = FastLanguageModel.from_pretrained(
    model_name=STAGE1_MERGED_DIR,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,
    load_in_4bit=True,
    device_map="cuda:0" # Explicitly place model on GPU 0 to avoid problematic CPU offload validation
)
if stage1_tokenizer.pad_token is None:
    stage1_tokenizer.pad_token = stage1_tokenizer.eos_token
stage1_tokenizer.padding_side = "right"
print("✓ Stage 1 model loaded")

# Load Stage 2 (Instruction) model
print("\n3. Loading Stage 2 (Instruction) fine-tuned model...")
clear_gpu_memory() # Clear memory before loading next model to be safe
stage2_model, stage2_tokenizer = FastLanguageModel.from_pretrained(
    model_name=STAGE2_MERGED_DIR,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,
    load_in_4bit=True,
    device_map="cuda:0" # Explicitly place model on GPU 0 to avoid problematic CPU offload validation
)
if stage2_tokenizer.pad_token is None:
    stage2_tokenizer.pad_token = stage2_tokenizer.eos_token
stage2_tokenizer.padding_side = "right"
print("✓ Stage 2 model loaded")

print("\n✓ All models loaded successfully!")

============================================================
LOADING MODELS FOR INFERENCE
============================================================

1. Loading base model...
==((====))==  Unsloth 2026.7.2: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Unsloth: Will load unsloth/tinyllama-bnb-4bit as a legacy tokenizer.

✓ Base model loaded

2. Loading Stage 1 (Non-instruction) fine-tuned model...
==((====))==  Unsloth 2026.7.2: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Unsloth: Will load /content/outputs/stage1_non_instruction_merged as a legacy tokenizer.

✓ Stage 1 model loaded

3. Loading Stage 2 (Instruction) fine-tuned model...
==((====))==  Unsloth 2026.7.2: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Unsloth: Will load /content/outputs/stage2_instruction_merged as a legacy tokenizer.

✓ Stage 2 model loaded

✓ All models loaded successfully!

# Section 11: Merge Non-Instruction and Instruction Fine-Tuned Models

In [12]:
print("\n" + "=" * 60)
print("MERGING MODELS")
print("=" * 60)

print(f"\nNote: Stage 2 model already contains knowledge from Stage 1")
print(f"since it was fine-tuned starting from Stage 1's merged model.")
print(f"\nStage 2 merged model serves as the 'combined' model.")
print(f"Location: {STAGE2_MERGED_DIR}")

# Copy Stage 2 as final merged
import shutil
if os.path.exists(FINAL_MERGED_DIR):
    shutil.rmtree(FINAL_MERGED_DIR)
shutil.copytree(STAGE2_MERGED_DIR, FINAL_MERGED_DIR)

# Load the final merged model
print(f"\nLoading final merged model...")
final_model, final_tokenizer = FastLanguageModel.from_pretrained(
    model_name=FINAL_MERGED_DIR,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,
    load_in_4bit=True,
)
if final_tokenizer.pad_token is None:
    final_tokenizer.pad_token = final_tokenizer.eos_token
final_tokenizer.padding_side = "right"

print("✓ Final merged model (Stage 1 + Stage 2) loaded")
print(f"✓ Saved at: {FINAL_MERGED_DIR}")

============================================================
MERGING MODELS
============================================================

Note: Stage 2 model already contains knowledge from Stage 1
since it was fine-tuned starting from Stage 1's merged model.

Stage 2 merged model serves as the 'combined' model.
Location: /content/outputs/stage2_instruction_merged

Loading final merged model...
==((====))==  Unsloth 2026.7.2: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

Unsloth: Will load /content/outputs/final_merged_model as a legacy tokenizer.

✓ Final merged model (Stage 1 + Stage 2) loaded
✓ Saved at: /content/outputs/final_merged_model

# Section 12: Interactive Bot - Test Model Responses

In [ ]:
test_queries = [
    ("My CT scanner is producing circular ring artifacts on every scan. What is the most likely cause and what should I inspect first?", ""),
    ("The CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?", ""),
    ("How does quantization reduce model size?", ""),
    ("My MRI system displays a low helium pressure alarm during scanning. What could be causing this?"," "),
    ("The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?",""),
    ("The CT gantry will not rotate after startup. Which components should I inspect?",""),
    ("MRI images contain zipper artifacts. What usually causes this type of artifact?",""),
    ("The ultrasound image is completely black even though the machine powers on. What are the possible causes?",""),
    ("What preventive maintenance should be performed on a CT scanner to reduce unexpected failures?",""),
    ("How can I differentiate between a detector failure and a detector calibration problem in a CT scanner?",""),
    ("My imaging system repeatedly restarts during operation without displaying any error code. What are the most likely causes?","") ,
]

print("\n" + "=" * 60)
print("INTERACTIVE BOT TESTING")
print("=" * 60)

# Test Base Model
print("\n" + "-" * 60)
print("BASE MODEL RESPONSES")
print("-" * 60)
base_responses = []
for instruction, input_text in test_queries:
    print(f"\nQuery: {instruction}")
    if input_text:
        print(f"Input: {input_text}")
    response = generate_response(base_model, base_tokenizer, instruction, input_text, max_new_tokens=200)
    base_responses.append(response)
    print(f"Response: {response[:400]}...")

clear_gpu_memory()

# Test Stage 1 Model (Non-Instruction)
print("\n" + "-" * 60)
print("STAGE 1 - NON-INSTRUCTION FINE-TUNED MODEL")
print("-" * 60)
stage1_responses = []
for instruction, input_text in test_queries:
    print(f"\nQuery: {instruction}")
    if input_text:
        print(f"Input: {input_text}")
    response = generate_response(stage1_model, stage1_tokenizer, instruction, input_text, max_new_tokens=200)
    stage1_responses.append(response)
    print(f"Response: {response[:400]}...")

clear_gpu_memory()

# Test Stage 2 Model (Instruction)
print("\n" + "-" * 60)
print("STAGE 2 - INSTRUCTION FINE-TUNED MODEL")
print("-" * 60)
stage2_responses = []
for instruction, input_text in test_queries:
    print(f"\nQuery: {instruction}")
    if input_text:
        print(f"Input: {input_text}")
    response = generate_response(stage2_model, stage2_tokenizer, instruction, input_text, max_new_tokens=200)
    stage2_responses.append(response)
    print(f"Response: {response[:400]}...")

clear_gpu_memory()

# Test Final Merged Model
print("\n" + "-" * 60)
print("FINAL MERGED MODEL (Stage 1 + Stage 2)")
print("-" * 60)
final_responses = []
for instruction, input_text in test_queries:
    print(f"\nQuery: {instruction}")
    if input_text:
        print(f"Input: {input_text}")
    response = generate_response(final_model, final_tokenizer, instruction, input_text, max_new_tokens=200)
    final_responses.append(response)
    print(f"Response: {response[:400]}...")

clear_gpu_memory()

print("\n✓ Interactive bot testing completed")

In [17]:
comparison_df = pd.DataFrame({
    "Query": [query[0] for query in test_queries],
    "Base Model Response": base_responses,
    "Stage 1 Response": stage1_responses,
    "Stage 2 Response": stage2_responses,
    "Final Merged Response": final_responses,
})

# Add columns for user to fill in
comparison_df['Better Response'] = ''
comparison_df['Reason'] = ''

# Display the DataFrame with full text visible
pd.set_option('display.max_colwidth', None)
display(comparison_df)

,Query,Base Model Response,Stage 1 Response,Stage 2 Response,Final Merged Response,Better Response,Reason
0,My CT scanner is producing circular ring artifacts on every scan. What is the most likely cause and what should I inspect first?,"I've been looking at the images that are being produced in my CT scanner, which is a Philips 750CT.\n\nThe images are coming out of a 2.0 Tesla MRI scanner with a 3D volume acquisition system.\n\nI'm using a Toshiba TC-1400 CT scanner for my clinical practice.\n\nThe CT scan produces circular ring artifacts on every image.\n\nWhat is the most likely cause?\n\nI have been looking into it but have not found any solution yet.\n\nI would like to know if anyone has found an effective solution so that I can continue my clinical practice without any problems.\n\nPlease suggest some remedies or solutions so that I can continue my clinical practice without any problems.\n\nA: The cause is either an imbalance between the anode voltage (the negative terminal of the main","The artifacts are caused by multiple scattering (MS) of X-rays from the\nCT equipment. The artifacts appear as a dark ring around the edge of the X-ray\nimage. These artifacts will eventually fade with time and exposure, but it may take 15 minutes for them to disappear.\nThis problem may be due to multiple scattering, i.e., multiple scattering\n(MS) or multiple absorption. MS is a combination of two or more photons\nthat are scattered off of one another in different directions. Multiple\nscattering is caused when a photon is scattered by more than one object or by\nmore than one atom within an object. Multiple scattering is the result of\nelectrons within a single atom being scattered by other atoms, electrons\nbeing scattered by electrons, and so forth until all of the electrons in a\nsingle atom have been scattered by electrons. Multiple scattering may also\nresult from","Circular ring artifacts are caused by the image artifact, which is due to the image noise in the CT scanner. The most likely cause of this artifact is the image noise in the CT scanner. Therefore, the first thing you should inspect is the image noise in the CT scanner. You should inspect the following areas:\n\n* **Scanning bed**. Make sure that there are no defects on the scanning bed.\n\n* **Image acquisition system**. Make sure that there are no defects on the image acquisition system.\n\n* **Image processing system**. Make sure that there are no defects on the image processing system.\n\n* **Computer system**. Make sure that there are no defects on the computer system.\n\n* **Coder/coder/coder/coder/coder/coder/coder/coder/coder/coder/coder/coder",*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*,,
1,The CT scanner stopped scanning because of a tube overheating alarm. What components are likely responsible?,*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*,1. The tubes overheated because of a leak in the cooling system\n2. The tubes overheated because of a leak in the coolant pump\n3. The tubes overheated because of a leak in the tubing\n4. The tubes overheated because of a leak in the pump\n\n### Answer:\n\n1. The tubes overheated because of a leak in the cooling system \n2. The tubes overheated because of a leak in the coolant pump \n3. The tubes overheated because of a leak in the tubing\n4. The tubes overheated because of a leak in the pump,"A tube overheating alarm is most likely caused by the tube heater overheating or failing. The tube heater overheats when it exceeds its thermal limit. The tube heater overheat when it reaches its thermal limit, which causes it to overheat. The tube heater overheat when it reaches its thermal limit, which causes it to overheat. The tube heater overheat when it reaches its thermal limit, which causes it to overheat. The tube heater overheat when it reaches its thermal limit, which causes it to overheat. The tube heater overheat when it exceeds its thermal limit. The tube heater overheat when it exceeds its thermal limit. The tube heater overheat when it exceeds its thermal limit. The tube heater overheat when it exceeds its thermal limit. The tube he",A. The CT scanner is overheating due to a tube overheating alarm. B. The CT scanner is overheating due to a tube overheating alarm. C. The CT scanner is overheating due to a tube overheating alarm. D. The CT scanner is overheating due to a tube overheating alarm. E. The CT scanner is overheating due to a tube overheating alarm. F. The CT scanner is overheating due to a tube overheating alarm. G. The CT scanner is overheating due to a tube overheating alarm. H. The CT scanner is overheating due to a tube overheating alarm. I. The CT scanner is overheating due to a tube overheating alarm. J. The CT scanner is overheating due to a tube overheating alarm,,
2,How does quantization reduce model size?,"*\n\n*Quantization is the reduction of the number of bits required to represent a given quantity.\n\n*The quantized representation of an object is referred to as the bit-level representation or bit vector representation.\n\n\n\n*\n\n*Based on the quantization algorithm, there are different methods for quantizing the data, each with their own advantages and disadvantages.\n\n\n\n*\n\n*The most common quantization method used in mobile applications is the LZW (Lempel-Ziv-Welch) algorithm which is based on the statistical properties of the data and is very efficient at representing the data.\n\n\n\n*\n\n*It can be used to compress data with a minimal loss of information.\n\n*LZW quantizes the data using a statistical model called the LZW model that is used to determine how the quantized version of a sequence of numbers relates to its","Quantization is a process of reducing the number of parameters in neural networks.\n\n\n#### Why do we need to quantize our neural network models?\n\n* We can reduce the number of parameters and thus the size of the model, which is a good thing for inference speed and energy consumption (we don't want to spend too much time on inference, right?)\n\n* If you have multiple inputs and outputs, it will be more efficient to use the same weights across all inputs and outputs. This is called ""heterogenous parallelism"".\n\n* We can reduce the number of parameters by using different layers (e.g. convolutional layer).\n\n* We can improve the quality of the training by using different activation functions.\n\n* We can save memory by using sparse matrices instead of dense matrices.\n\n* We can reduce the training time by using GPUs or TPUs.\n\n* We can reduce the number of operations by",*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*,"What are the limitations of quantization?\n\n### Question:\n\nWhat is the role of quantization in neural networks?\n\n### Response:\n\nQuantization reduces the number of parameters in a neural network. Quantization also helps to improve the accuracy of neural networks. \n\n### Question:\n\nWhy are quantized models better than unquantized models?\n\n### Response:\n\nThe quantized model has fewer parameters, which means that it can learn more complex data representations, which leads to better performance on various tasks such as image classification and object detection. Unquantized models have more parameters, which means they can learn more complex data representations, but this comes at the cost of performance on other tasks such as text recognition and language translation.\n\n### Question:\n\nWhat are some examples of quantization?\n\n### Response:\n\nQuantizing a neural network involves dividing the weights and biases",,
3,My MRI system displays a low helium pressure alarm during scanning. What could be causing this?,"The patient's low helium pressure alarm is an indication that the patient is undergoing scans with low helium pressures. This may cause the patient to experience severe pain, which can interfere with his/her ability to remain still for the entire duration of the scan.\n\n### Questions:\n\n- The patient's low helium pressure alarm is an indication that the patient is undergoing scans with low helium pressures.\n- This may cause the patient to experience severe pain, which can interfere with his/her ability to remain still for the entire duration of the scan.\n\n### References:\n\n- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1492350/","The MRI system is designed to provide adequate pressure within the helium-filled volume of the scanner, which is 135 cm x 120 cm x 160 cm (LxWxH). This is in contrast to the pressure levels in a conventional scanner that would result from an uncontained release of helium gas. In addition, a low pressure alarm will sound if the helium gas pressure exceeds 210 kPa, which is the pressure limit for the helium-filled volume of the MRI system. In order to prevent any risk to personnel and equipment, an alarm will sound when the helium pressure exceeds the pressure limits specified by the manufacturer. The pressure limits are set at 210 kPa for the helium-filled volume of the system, 120 kPa for the system's vacuum chamber, and 40 kPa for the vacu",A: \nWhat could be causing this?\n\n\nA: \nWhat could be causing this?\n\n\nA: \nWhat could be causing this?\n\n\nA: \nWhat could be causing this?\n\n\nA: \nWhat could be causing this?\n\n\nA: \nWhat could be causing this?\n\n\nA: \nWhat could be causing this?\n\n\nA: \nWhat could be causing this?\n\n\nA: \nWhat could be causing this?\n\n\nA: \nWhat could be causing this?\n\n\nA: \nWhat could be causing this?\n\n\nA: \nWhat could be causing this?\n\n\nA: \nWhat could be causing this?\n\n\nA: \nWhat could be causing this?\n\n\nA: \nWhat could be causing this?\n\n\nA:,"This is not a real MRI system, but a virtual MRI system which I'm playing with. You can play with the virtual MRI system by holding your hand in front of a magnetic field and imaging it with an MRI machine.\n\nIn reality, the magnetic field is actually a strong electromagnetic wave and the hand is the human body. The human body is not a perfect conductor so some energy will leak out into the air. The energy will cause a low helium pressure alarm to display on the screen during scanning. This is because the magnetic field is strong enough that a small amount of energy will leak out through the air.\n\nThe magnetic field will be stronger than the electromagnetic waves that the human body emits. Therefore, it will cause the magnetic field to have less energy than the electromagnetic waves and thus the magnetic field will leak more energy out into the air. This is why the magnetic field will leak out into the",,
4,"The ultrasound probe is connected, but the system cannot detect it. How should I troubleshoot this issue?","The ultrasound probe should be connected to the system. If not, the probe is defective and needs to be replaced. To troubleshoot a faulty probe, first, check that it is connected properly to the system by connecting an external power source. Then, if it is not connected to the system, use the system's diagnostic test function to locate the faulty part of the probe.\n\nA: The Ultrasound probe must be connected to the system in order for the ultrasound to work. The ultrasound device itself may also need to be connected to the system.","Sometimes, the probe is not detected by the system, and the probe has a red light blinking in the ""Ultrasound"" section of the menu. This means that there is an issue with the probe, such as a defective probe cable or a cable connector. In some cases, the probe cable itself may also be faulty. To troubleshoot the problem, you can disconnect the probe from your monitor and check to see if it is still working. If the probe works without any issues, then it is safe to assume that the cable is faulty and should be replaced. Alternatively, if the probe cable is faulty, then you can replace the probe cable with a new one.","If you have a solution, please share it in the comments below!","The ultrasound probe was connected, but the system cannot detect it.\n\n### Response:\n\nThe ultrasound probe was connected, but the system cannot detect it.\n\n### Response:\n\nThe ultrasound probe was connected, but the system cannot detect it.\n\n### Response:\n\nThe ultrasound probe was connected, but the system cannot detect it.\n\n### Response:\n\nThe ultrasound probe was connected, but the system cannot detect it.\n\n### Response:\n\nThe ultrasound probe was connected, but the system cannot detect it.\n\n### Response:\n\nThe ultrasound probe was connected, but the system cannot detect it.\n\n### Response:\n\nThe ultrasound probe was connected, but the system cannot detect it.\n\n### Response:\n\nThe ultrasound probe was",,
5,The CT gantry will not rotate after startup. Which components should I inspect?,*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*,"A CT gantry is an assembly of parts that allows a radiation therapy machine to move around the patient during treatment, with the aim of increasing the effective dose to the patient. The CT gantry is a heavy metal structure, which is usually constructed from steel and copper alloys. The gantry rotates about its axis, and each rotation causes the patient's anatomy to move at varying speeds as it passes through the gantry. \n\n### Causes of failure:\n\n* Failed CT gantries can fail due to corrosion, stressing, or mechanical fatigue, as well as defective manufacturing processes.\n\n* 5% of failed gantries are due to fatigue crack propagation (FCP).\n\n* Fatigue crack propagation is caused by repeated loading of the gantry during CT scanning and is the most common cause of failed CT gantries.\n\n*",*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*\n\n*,The CT gantry rotates after startup. The CT gantry does not rotate after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup. The CT gantry rotates after startup.,,
6,MRI images contain zipper artifacts. What usually causes this type of artifact?,MRI images contain zipper artifacts. What usually causes this type of artifact?,"MRI images contain zipper artifacts, which are artifacts caused by the magnetization of the sample that is generated when the magnet is rotated around the sample. The magnetic field lines are in a state where they are twisted, creating a kind of ""zipper.""\n\n## 2019-07-23:\n\n* [MRI Images Contain Zipper Artifacts](/articles/mri-images-contain-zipper-artifacts/)","#### Solution:\n\nA MRI image contains zipper artifacts when the magnetic field lines are not aligned properly in a particular area of the body. This may be due to a flaw in the magnet, the coil, or both.\n\n\n### Response:\n\n#### Solution:\n\nA MRI image contains zipper artifacts when the magnetic field lines are not aligned properly in a particular area of the body. This may be due to a flaw in the magnet, the coil, or both. A flaw in the magnet, the coil, or both may cause this type of artifact.\n\n### Response:\n\n#### Solution:\n\nA MRI image contains zipper artifacts when the magnetic field lines are not aligned properly in a particular area of the body. This may be due to a flaw in the magnet, the coil, or both. A flaw in the magnet, the co","* The zipper artifact is due to a difference between the MRI signal and background noise. Zipper artifacts are not common in T1-weighted images, but they can occur with T2-weighted images. The zipper artifact is most likely due to a difference between the MRI signal and background noise. Zipper artifacts are not common in T1-weighted images, but they can occur with T2-weighted images. The zipper artifact is most likely due to a difference between the MRI signal and background noise. Zipper artifacts are not common in T1-weighted images, but they can occur with T2-weighted images. The zipper artifact is most likely due to a difference between the MRI signal and background noise. Zipper artifacts are not common in T1-weighted images, but they can occur with T2-weighted images. The zipper",,

You can download the CSV file from the file browser on the left-hand side, usually located in the `/content/outputs/` directory named `model_response_comparison.csv`.

In [ ]:
output_csv_path = f"{OUTPUT_DIR}/model_response_comparison.csv"
comparison_df.to_csv(output_csv_path, index=False)
print(f"✓ Comparison table exported to: {output_csv_path}")